-- 1、基础表结构
-- 用途：创建系统基础表：门店、账号资料、顾客、员工、跟进、每日复盘。
-- 说明：本段可单独运行；只补齐表、字段、索引和基础门店数据，不删除旧字段。

begin;

create table if not exists public.stores (
  id bigint generated always as identity primary key,
  name text,
  created_at timestamptz default now()
);

alter table public.stores
  add column if not exists name text,
  add column if not exists created_at timestamptz default now();

create unique index if not exists idx_stores_name_unique on public.stores (name);
create index if not exists idx_stores_name on public.stores (name);

insert into public.stores (name)
values
('龙泉1店'),
('龙泉2店'),
('龙泉金龙店'),
('郫县1店')
on conflict (name) do nothing;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id text,
  name text,
  role text,
  store text,
  created_at timestamptz default now()
);

alter table public.profiles
  add column if not exists user_id text,
  add column if not exists name text,
  add column if not exists role text,
  add column if not exists store text,
  add column if not exists created_at timestamptz default now();

create index if not exists idx_profiles_user_id on public.profiles (user_id);
create index if not exists idx_profiles_role on public.profiles (role);
create index if not exists idx_profiles_store on public.profiles (store);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  age numeric,
  birthday date,
  store text,
  owner text,
  level text,
  last_visit date,
  follow_status text,
  last_follow_result text,
  last_follow_time date,
  next_follow_time date,
  follow_note text,
  today_task_completed_at timestamptz,
  created_at timestamptz default now()
);

alter table public.customers
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists age numeric,
  add column if not exists birthday date,
  add column if not exists store text,
  add column if not exists owner text,
  add column if not exists level text,
  add column if not exists last_visit date,
  add column if not exists follow_status text,
  add column if not exists last_follow_result text,
  add column if not exists last_follow_time date,
  add column if not exists next_follow_time date,
  add column if not exists follow_note text,
  add column if not exists today_task_completed_at timestamptz,
  add column if not exists created_at timestamptz default now();

create index if not exists idx_customers_store on public.customers (store);
create index if not exists idx_customers_owner on public.customers (owner);
create index if not exists idx_customers_last_visit on public.customers (last_visit);
create index if not exists idx_customers_phone_lookup on public.customers (phone);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  store text,
  role text,
  note text,
  base_salary numeric default 0,
  social_security_allowance numeric default 0,
  full_attendance_bonus numeric default 0,
  seniority_salary numeric default 0,
  entry_date date,
  is_active boolean default true,
  is_technical_department boolean default false,
  salary_plan_type text,
  today_followups numeric default 0,
  today_appointments numeric default 0,
  today_arrivals numeric default 0,
  today_deals numeric default 0,
  today_sales numeric default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.employees
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists note text,
  add column if not exists base_salary numeric default 0,
  add column if not exists social_security_allowance numeric default 0,
  add column if not exists full_attendance_bonus numeric default 0,
  add column if not exists seniority_salary numeric default 0,
  add column if not exists entry_date date,
  add column if not exists is_active boolean default true,
  add column if not exists is_technical_department boolean default false,
  add column if not exists salary_plan_type text,
  add column if not exists today_followups numeric default 0,
  add column if not exists today_appointments numeric default 0,
  add column if not exists today_arrivals numeric default 0,
  add column if not exists today_deals numeric default 0,
  add column if not exists today_sales numeric default 0,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create index if not exists idx_employees_store on public.employees (store);
create index if not exists idx_employees_role on public.employees (role);
create index if not exists idx_employees_name on public.employees (name);

create table if not exists public.followups (
  id bigint generated by default as identity primary key,
  customer_id bigint,
  customer_name text,
  customer_phone text,
  store text,
  owner text,
  method text,
  content text,
  feedback text,
  issue_type text,
  has_appointment boolean default false,
  appointment_time date,
  has_deal boolean default false,
  deal_amount numeric default 0,
  next_follow_time date,
  created_at timestamptz default now()
);

alter table public.followups
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists store text,
  add column if not exists owner text,
  add column if not exists method text,
  add column if not exists content text,
  add column if not exists feedback text,
  add column if not exists issue_type text,
  add column if not exists has_appointment boolean default false,
  add column if not exists appointment_time date,
  add column if not exists has_deal boolean default false,
  add column if not exists deal_amount numeric default 0,
  add column if not exists next_follow_time date,
  add column if not exists created_at timestamptz default now();

create index if not exists idx_followups_store on public.followups (store);
create index if not exists idx_followups_owner on public.followups (owner);
create index if not exists idx_followups_customer_id on public.followups (customer_id);
create index if not exists idx_followups_created_at on public.followups (created_at);

create table if not exists public.daily_reviews (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  invite_rate numeric default 0,
  appointment_rate numeric default 0,
  arrival_rate numeric default 0,
  deal_rate numeric default 0,
  deal_amount numeric default 0,
  unfinished_reason text,
  tomorrow_action text,
  created_at timestamptz default now()
);

alter table public.daily_reviews
  add column if not exists date date,
  add column if not exists store text,
  add column if not exists invite_rate numeric default 0,
  add column if not exists appointment_rate numeric default 0,
  add column if not exists arrival_rate numeric default 0,
  add column if not exists deal_rate numeric default 0,
  add column if not exists deal_amount numeric default 0,
  add column if not exists unfinished_reason text,
  add column if not exists tomorrow_action text,
  add column if not exists created_at timestamptz default now();

create index if not exists idx_daily_reviews_store on public.daily_reviews (store);
create index if not exists idx_daily_reviews_date on public.daily_reviews (date);
create index if not exists idx_daily_reviews_created_at on public.daily_reviews (created_at);

update public.profiles
set role = case role
  when '老板' then 'boss'
  when '店长' then 'manager'
  when '美容师' then 'beautician'
  else role
end
where role in ('老板', '店长', '美容师');

update public.employees
set role = case role
  when '老板' then 'boss'
  when '店长' then 'manager'
  when '美容师' then 'beautician'
  else role
end
where role in ('老板', '店长', '美容师');

commit;
