-- 2、目标系统
-- 用途：创建门店目标管理表 store_targets。
-- 说明：本段可单独运行；不会重复建表或重复建索引。

begin;

create table if not exists public.store_targets (
  id bigint generated by default as identity primary key,
  month text,
  store text,
  monthly_target numeric default 0,
  daily_target numeric default 0,
  current_sales numeric default 0,
  completion_rate numeric default 0,
  remaining_amount numeric default 0,
  created_at timestamptz default now()
);

alter table public.store_targets
  add column if not exists month text,
  add column if not exists store text,
  add column if not exists monthly_target numeric default 0,
  add column if not exists daily_target numeric default 0,
  add column if not exists current_sales numeric default 0,
  add column if not exists completion_rate numeric default 0,
  add column if not exists remaining_amount numeric default 0,
  add column if not exists created_at timestamptz default now();

create unique index if not exists idx_store_targets_month_store on public.store_targets (month, store);
create index if not exists idx_store_targets_store on public.store_targets (store);
create index if not exists idx_store_targets_month on public.store_targets (month);

commit;
