-- 3、员工业绩日报
-- 用途：创建员工业绩日报表 employee_performance_reports。
-- 说明：本段可单独运行；字段名统一使用 date、arrivals、service_sales 等当前前端字段。

begin;

create table if not exists public.employee_performance_reports (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  employee text,
  arrivals numeric default 0,
  service_sales numeric default 0,
  consume_sales numeric default 0,
  cash_sales numeric default 0,
  new_customers numeric default 0,
  repeat_customers numeric default 0,
  upsell_amount numeric default 0,
  total_sales numeric default 0,
  unit_price numeric default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.employee_performance_reports
  add column if not exists date date,
  add column if not exists store text,
  add column if not exists employee text,
  add column if not exists arrivals numeric default 0,
  add column if not exists service_sales numeric default 0,
  add column if not exists consume_sales numeric default 0,
  add column if not exists cash_sales numeric default 0,
  add column if not exists new_customers numeric default 0,
  add column if not exists repeat_customers numeric default 0,
  add column if not exists upsell_amount numeric default 0,
  add column if not exists total_sales numeric default 0,
  add column if not exists unit_price numeric default 0,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.employee_performance_reports
set total_sales = coalesce(service_sales, 0) + coalesce(consume_sales, 0) + coalesce(cash_sales, 0) + coalesce(upsell_amount, 0)
where total_sales is null or total_sales = 0;

update public.employee_performance_reports
set unit_price = case when coalesce(arrivals, 0) > 0 then total_sales / arrivals else 0 end
where unit_price is null or unit_price = 0;

create index if not exists idx_employee_performance_reports_date on public.employee_performance_reports (date);
create index if not exists idx_employee_performance_reports_store on public.employee_performance_reports (store);
create index if not exists idx_employee_performance_reports_employee on public.employee_performance_reports (employee);

commit;
