-- 4、员工业绩月报
-- 用途：创建开单/业绩记录表 performance_records，供月报、手工费和提成计算使用。
-- 说明：本段可单独运行；月报由前端按 performance_records 和 employee_performance_reports 自动汇总。

begin;

create table if not exists public.performance_records (
  id bigint generated by default as identity primary key,
  date date,
  month text,
  store_id bigint,
  store_name text,
  customer_id bigint,
  customer_name text,
  project_id bigint,
  project_name text,
  project_category text,
  amount numeric default 0,
  consume_amount numeric default 0,
  payment_type text,
  service_employee_id bigint,
  service_employee_name text,
  sales_employee_id bigint,
  sales_employee_name text,
  consultant_id bigint,
  consultant_name text,
  quantity numeric default 1,
  manual_commission_amount numeric default 0,
  remark text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.performance_records
  add column if not exists date date,
  add column if not exists month text,
  add column if not exists store_id bigint,
  add column if not exists store_name text,
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists project_id bigint,
  add column if not exists project_name text,
  add column if not exists project_category text,
  add column if not exists amount numeric default 0,
  add column if not exists consume_amount numeric default 0,
  add column if not exists payment_type text,
  add column if not exists service_employee_id bigint,
  add column if not exists service_employee_name text,
  add column if not exists sales_employee_id bigint,
  add column if not exists sales_employee_name text,
  add column if not exists consultant_id bigint,
  add column if not exists consultant_name text,
  add column if not exists quantity numeric default 1,
  add column if not exists manual_commission_amount numeric default 0,
  add column if not exists remark text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

update public.performance_records
set month = substring(date::text from 1 for 7)
where month is null and date is not null;

create index if not exists idx_performance_records_month on public.performance_records (month);
create index if not exists idx_performance_records_date on public.performance_records (date);
create index if not exists idx_performance_records_store_name on public.performance_records (store_name);
create index if not exists idx_performance_records_service_employee_name on public.performance_records (service_employee_name);
create index if not exists idx_performance_records_sales_employee_name on public.performance_records (sales_employee_name);

commit;
