-- 5、工资结算系统
-- 用途：创建项目提成设置、员工每日统计和工资结算所需字段。
-- 说明：本段可单独运行；包含项目手工费种子数据，不重复插入。

begin;

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  store text,
  role text,
  note text,
  base_salary numeric default 0,
  social_security_allowance numeric default 0,
  full_attendance_bonus numeric default 0,
  seniority_salary numeric default 0,
  entry_date date,
  is_active boolean default true,
  is_technical_department boolean default false,
  salary_plan_type text,
  today_followups numeric default 0,
  today_appointments numeric default 0,
  today_arrivals numeric default 0,
  today_deals numeric default 0,
  today_sales numeric default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.employees
  add column if not exists base_salary numeric default 0,
  add column if not exists social_security_allowance numeric default 0,
  add column if not exists full_attendance_bonus numeric default 0,
  add column if not exists seniority_salary numeric default 0,
  add column if not exists entry_date date,
  add column if not exists is_active boolean default true,
  add column if not exists is_technical_department boolean default false,
  add column if not exists salary_plan_type text,
  add column if not exists today_followups numeric default 0,
  add column if not exists today_appointments numeric default 0,
  add column if not exists today_arrivals numeric default 0,
  add column if not exists today_deals numeric default 0,
  add column if not exists today_sales numeric default 0,
  add column if not exists updated_at timestamptz default now();

create table if not exists public.employee_daily_stats (
  id bigint generated by default as identity primary key,
  date date,
  employee_id bigint,
  employee_name text,
  phone text,
  store text,
  role text,
  followups numeric default 0,
  appointments numeric default 0,
  arrivals numeric default 0,
  deals numeric default 0,
  sales numeric default 0,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.employee_daily_stats
  add column if not exists date date,
  add column if not exists employee_id bigint,
  add column if not exists employee_name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists followups numeric default 0,
  add column if not exists appointments numeric default 0,
  add column if not exists arrivals numeric default 0,
  add column if not exists deals numeric default 0,
  add column if not exists sales numeric default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists idx_employee_daily_stats_date_employee_id on public.employee_daily_stats (date, employee_id);
create index if not exists idx_employee_daily_stats_date on public.employee_daily_stats (date);
create index if not exists idx_employee_daily_stats_store on public.employee_daily_stats (store);
create index if not exists idx_employee_daily_stats_employee_id on public.employee_daily_stats (employee_id);

create table if not exists public.project_commission_settings (
  id bigint generated by default as identity primary key,
  project_name text,
  category text,
  manual_commission numeric default 0,
  duration_minutes numeric,
  unit text default '次',
  is_active boolean default true,
  remark text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.project_commission_settings
  add column if not exists project_name text,
  add column if not exists category text,
  add column if not exists manual_commission numeric default 0,
  add column if not exists duration_minutes numeric,
  add column if not exists unit text default '次',
  add column if not exists is_active boolean default true,
  add column if not exists remark text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create index if not exists idx_project_commission_settings_project_name on public.project_commission_settings (project_name);
create unique index if not exists idx_project_commission_settings_project_name_unique on public.project_commission_settings (project_name);
create index if not exists idx_project_commission_settings_category on public.project_commission_settings (category);

insert into public.project_commission_settings (project_name, category, manual_commission, duration_minutes, unit, is_active, remark)
values
('面部基础护理', 'face', 3, 60, '次', true, ''),
('眼八宝', 'face', 3, 30, '次', true, ''),
('面部香薰', 'face', 5, 60, '次', true, ''),
('颈护', 'body', 3, 30, '次', true, ''),
('肩颈调理', 'body', 8, 60, '次', true, ''),
('胸部保养', 'body', 8, 45, '次', true, ''),
('卵巢保养', 'body', 8, 45, '次', true, ''),
('肾保', 'body', 8, 45, '次', true, ''),
('肝胆排毒', 'body', 15, 90, '次', true, ''),
('淋巴', 'body', 8, 45, '次', true, ''),
('腿部保养', 'body', 8, 45, '次', true, ''),
('臀疗', 'body', 15, 45, '次', true, ''),
('头疗', 'body', 3, 45, '次', true, ''),
('艾灸', 'moxibustion', 0.5, null, '个', true, ''),
('泥灸', 'moxibustion', 1, null, '张', true, ''),
('贝罗娜', 'high_end', 15, null, '次', true, ''),
('中胚', 'high_end', 15, null, '次', true, ''),
('祛木', 'high_end', 15, null, '次', true, ''),
('私密SAP', 'high_end', 20, null, '次', true, ''),
('苗药', 'high_end', 8, null, '次', true, ''),
('童颜抗衰仪', 'high_end', 15, null, '次', true, ''),
('魔术刀', 'high_end', 15, 40, '次', true, '局部15元'),
('骨龄抗衰', 'high_end', 20, 40, '次', true, ''),
('逆龄炮', 'high_end', 15, 30, '次', true, '')
on conflict (project_name) do nothing;

commit;
