-- 6、RLS权限
-- 用途：创建/刷新所有表的 Supabase RLS 权限。
-- 说明：本段建议最后执行；包含最小 create table if not exists，确保单独 Run 不因表不存在中断。

begin;

create table if not exists public.stores (id bigint generated always as identity primary key, name text, created_at timestamptz default now());
create table if not exists public.profiles (id bigint generated by default as identity primary key, user_id text, name text, role text, store text, created_at timestamptz default now());
create table if not exists public.customers (id bigint generated by default as identity primary key, name text, phone text, store text, owner text, created_at timestamptz default now());
create table if not exists public.employees (id bigint generated by default as identity primary key, name text, store text, role text, created_at timestamptz default now());
create table if not exists public.employee_daily_stats (id bigint generated by default as identity primary key, date date, employee_id bigint, employee_name text, store text, role text, created_at timestamptz default now());
create table if not exists public.employee_performance_reports (id bigint generated by default as identity primary key, date date, store text, employee text, created_at timestamptz default now());
create table if not exists public.store_targets (id bigint generated by default as identity primary key, month text, store text, created_at timestamptz default now());
create table if not exists public.project_commission_settings (id bigint generated by default as identity primary key, project_name text, category text, created_at timestamptz default now());
create table if not exists public.performance_records (id bigint generated by default as identity primary key, date date, store_name text, service_employee_name text, sales_employee_name text, created_at timestamptz default now());
create table if not exists public.followups (id bigint generated by default as identity primary key, store text, owner text, created_at timestamptz default now());
create table if not exists public.daily_reviews (id bigint generated by default as identity primary key, date date, store text, created_at timestamptz default now());

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select case
    when role = 'admin' then 'boss'
    when role in ('employee', 'consultant', 'technical_teacher') then 'beautician'
    when role = 'regional_manager' then 'boss'
    else role
  end
  from public.profiles
  where user_id = auth.uid()::text
  limit 1
$$;

create or replace function public.current_profile_store()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select store from public.profiles where user_id = auth.uid()::text limit 1
$$;

create or replace function public.current_profile_name()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select name from public.profiles where user_id = auth.uid()::text limit 1
$$;

alter table public.stores enable row level security;
alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.employees enable row level security;
alter table public.employee_daily_stats enable row level security;
alter table public.employee_performance_reports enable row level security;
alter table public.store_targets enable row level security;
alter table public.project_commission_settings enable row level security;
alter table public.performance_records enable row level security;
alter table public.followups enable row level security;
alter table public.daily_reviews enable row level security;

drop policy if exists stores_authenticated_select on public.stores;
create policy stores_authenticated_select on public.stores for select to authenticated using (true);

drop policy if exists profiles_select_scope on public.profiles;
create policy profiles_select_scope on public.profiles for select to authenticated
using (user_id = auth.uid()::text or public.current_profile_role() = 'boss');

drop policy if exists profiles_update_self_or_boss on public.profiles;
create policy profiles_update_self_or_boss on public.profiles for update to authenticated
using (user_id = auth.uid()::text or public.current_profile_role() = 'boss')
with check (user_id = auth.uid()::text or public.current_profile_role() = 'boss');

drop policy if exists customers_select_scope on public.customers;
create policy customers_select_scope on public.customers for select to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
);

drop policy if exists customers_insert_scope on public.customers;
create policy customers_insert_scope on public.customers for insert to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists customers_update_scope on public.customers;
create policy customers_update_scope on public.customers for update to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and owner = public.current_profile_name())
);

drop policy if exists customers_delete_scope on public.customers;
create policy customers_delete_scope on public.customers for delete to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employees_select_scope on public.employees;
create policy employees_select_scope on public.employees for select to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and name = public.current_profile_name())
);

drop policy if exists employees_insert_scope on public.employees;
create policy employees_insert_scope on public.employees for insert to authenticated
with check (
  public.current_profile_role() = 'boss'
);

drop policy if exists employees_update_scope on public.employees;
create policy employees_update_scope on public.employees for update to authenticated
using (
  public.current_profile_role() = 'boss'
)
with check (
  public.current_profile_role() = 'boss'
);

drop policy if exists employees_delete_scope on public.employees;
create policy employees_delete_scope on public.employees for delete to authenticated
using (
  public.current_profile_role() = 'boss'
);

drop policy if exists employee_daily_stats_select_scope on public.employee_daily_stats;
create policy employee_daily_stats_select_scope on public.employee_daily_stats for select to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and employee_name = public.current_profile_name())
);

drop policy if exists employee_daily_stats_insert_scope on public.employee_daily_stats;
create policy employee_daily_stats_insert_scope on public.employee_daily_stats for insert to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employee_daily_stats_update_scope on public.employee_daily_stats;
create policy employee_daily_stats_update_scope on public.employee_daily_stats for update to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employee_performance_reports_select_scope on public.employee_performance_reports;
create policy employee_performance_reports_select_scope on public.employee_performance_reports for select to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and employee = public.current_profile_name())
);

drop policy if exists employee_performance_reports_insert_scope on public.employee_performance_reports;
create policy employee_performance_reports_insert_scope on public.employee_performance_reports for insert to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and employee = public.current_profile_name())
);

drop policy if exists employee_performance_reports_update_scope on public.employee_performance_reports;
create policy employee_performance_reports_update_scope on public.employee_performance_reports for update to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and employee = public.current_profile_name())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and employee = public.current_profile_name())
);

drop policy if exists employee_performance_reports_delete_scope on public.employee_performance_reports;
create policy employee_performance_reports_delete_scope on public.employee_performance_reports for delete to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and employee = public.current_profile_name())
);

drop policy if exists store_targets_select_scope on public.store_targets;
create policy store_targets_select_scope on public.store_targets for select to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists store_targets_insert_scope on public.store_targets;
create policy store_targets_insert_scope on public.store_targets for insert to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists store_targets_update_scope on public.store_targets;
create policy store_targets_update_scope on public.store_targets for update to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists store_targets_delete_scope on public.store_targets;
create policy store_targets_delete_scope on public.store_targets for delete to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists project_commission_settings_select_scope on public.project_commission_settings;
create policy project_commission_settings_select_scope on public.project_commission_settings for select to authenticated using (
  public.current_profile_role() = 'boss'
);

drop policy if exists project_commission_settings_insert_scope on public.project_commission_settings;
create policy project_commission_settings_insert_scope on public.project_commission_settings for insert to authenticated
with check (public.current_profile_role() = 'boss');

drop policy if exists project_commission_settings_update_scope on public.project_commission_settings;
create policy project_commission_settings_update_scope on public.project_commission_settings for update to authenticated
using (public.current_profile_role() = 'boss')
with check (public.current_profile_role() = 'boss');

drop policy if exists performance_records_select_scope on public.performance_records;
create policy performance_records_select_scope on public.performance_records for select to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and (service_employee_name = public.current_profile_name() or sales_employee_name = public.current_profile_name()))
);

drop policy if exists performance_records_insert_scope on public.performance_records;
create policy performance_records_insert_scope on public.performance_records for insert to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store_name = public.current_profile_store() and (service_employee_name = public.current_profile_name() or sales_employee_name = public.current_profile_name()))
);

drop policy if exists performance_records_update_scope on public.performance_records;
create policy performance_records_update_scope on public.performance_records for update to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and (service_employee_name = public.current_profile_name() or sales_employee_name = public.current_profile_name()))
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store_name = public.current_profile_store() and (service_employee_name = public.current_profile_name() or sales_employee_name = public.current_profile_name()))
);

drop policy if exists performance_records_delete_scope on public.performance_records;
create policy performance_records_delete_scope on public.performance_records for delete to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
);

drop policy if exists followups_select_scope on public.followups;
create policy followups_select_scope on public.followups for select to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
);

drop policy if exists followups_insert_scope on public.followups;
create policy followups_insert_scope on public.followups for insert to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and owner = public.current_profile_name())
);

drop policy if exists followups_update_scope on public.followups;
create policy followups_update_scope on public.followups for update to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and owner = public.current_profile_name())
);

drop policy if exists followups_delete_scope on public.followups;
create policy followups_delete_scope on public.followups for delete to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
);

drop policy if exists daily_reviews_select_scope on public.daily_reviews;
create policy daily_reviews_select_scope on public.daily_reviews for select to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists daily_reviews_insert_scope on public.daily_reviews;
create policy daily_reviews_insert_scope on public.daily_reviews for insert to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists daily_reviews_update_scope on public.daily_reviews;
create policy daily_reviews_update_scope on public.daily_reviews for update to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists daily_reviews_delete_scope on public.daily_reviews;
create policy daily_reviews_delete_scope on public.daily_reviews for delete to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

commit;
