-- 开单收银 cashier_orders 初始化脚本
-- 可单独在 Supabase SQL Editor 执行。

begin;

create table if not exists public.cashier_orders (
  id bigint generated by default as identity primary key,
  order_no text,
  date date,
  month text,
  store_id bigint,
  store_name text,
  customer_id bigint,
  customer_name text,
  customer_phone text,
  project_id bigint,
  project_name text,
  project_category text,
  quantity numeric default 1,
  original_amount numeric default 0,
  discount_amount numeric default 0,
  actual_amount numeric default 0,
  consume_amount numeric default 0,
  payment_type text,
  service_employee_id bigint,
  service_employee_name text,
  sales_employee_id bigint,
  sales_employee_name text,
  consultant_id bigint,
  consultant_name text,
  manual_commission_amount numeric default 0,
  remark text,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.cashier_orders
  add column if not exists order_no text,
  add column if not exists date date,
  add column if not exists month text,
  add column if not exists store_id bigint,
  add column if not exists store_name text,
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists project_id bigint,
  add column if not exists project_name text,
  add column if not exists project_category text,
  add column if not exists quantity numeric default 1,
  add column if not exists original_amount numeric default 0,
  add column if not exists discount_amount numeric default 0,
  add column if not exists actual_amount numeric default 0,
  add column if not exists consume_amount numeric default 0,
  add column if not exists payment_type text,
  add column if not exists service_employee_id bigint,
  add column if not exists service_employee_name text,
  add column if not exists sales_employee_id bigint,
  add column if not exists sales_employee_name text,
  add column if not exists consultant_id bigint,
  add column if not exists consultant_name text,
  add column if not exists manual_commission_amount numeric default 0,
  add column if not exists remark text,
  add column if not exists status text default 'active',
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

create unique index if not exists idx_cashier_orders_order_no_unique on public.cashier_orders (order_no);
create index if not exists idx_cashier_orders_month on public.cashier_orders (month);
create index if not exists idx_cashier_orders_date on public.cashier_orders (date);
create index if not exists idx_cashier_orders_store_name on public.cashier_orders (store_name);
create index if not exists idx_cashier_orders_service_employee_name on public.cashier_orders (service_employee_name);
create index if not exists idx_cashier_orders_sales_employee_name on public.cashier_orders (sales_employee_name);
create index if not exists idx_cashier_orders_consultant_name on public.cashier_orders (consultant_name);
create index if not exists idx_cashier_orders_status on public.cashier_orders (status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_cashier_orders_updated_at on public.cashier_orders;
create trigger set_cashier_orders_updated_at
before update on public.cashier_orders
for each row
execute function public.set_updated_at();

alter table public.cashier_orders enable row level security;

drop policy if exists cashier_orders_select_scope on public.cashier_orders;
create policy cashier_orders_select_scope
on public.cashier_orders for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and (
    service_employee_name = public.current_profile_name()
    or sales_employee_name = public.current_profile_name()
    or consultant_name = public.current_profile_name()
  ))
);

drop policy if exists cashier_orders_insert_scope on public.cashier_orders;
create policy cashier_orders_insert_scope
on public.cashier_orders for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
);

drop policy if exists cashier_orders_update_scope on public.cashier_orders;
create policy cashier_orders_update_scope
on public.cashier_orders for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
);

drop policy if exists cashier_orders_delete_scope on public.cashier_orders;
create policy cashier_orders_delete_scope
on public.cashier_orders for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
);

insert into public.cashier_orders (
  order_no, date, month, store_name, customer_name, customer_phone, project_name, project_category,
  quantity, original_amount, discount_amount, actual_amount, consume_amount, payment_type,
  service_employee_name, sales_employee_name, consultant_name, manual_commission_amount, remark, status
) values
('YM202605180101','2026-05-18','2026-05','龙泉1店','张姐','13800000001','肩颈调理','body',1,398,0,398,120,'wechat','胡语','胡语','',8,'测试订单','active'),
('YM202605180102','2026-05-18','2026-05','龙泉1店','王姐','13800000002','臀疗','body',1,680,80,600,180,'cash','琳娜','胡语','',15,'测试订单','active'),
('YM202605170103','2026-05-17','2026-05','龙泉1店','李姐','13800000003','肝胆排毒','body',1,980,0,980,260,'alipay','胡语','琳娜','',15,'测试订单','active'),
('YM202605160104','2026-05-16','2026-05','龙泉1店','赵姐','13800000004','面部基础护理','face',2,596,96,500,160,'card','琳娜','琳娜','',6,'测试订单','active'),
('YM202605150105','2026-05-15','2026-05','龙泉1店','周姐','13800000005','骨龄抗衰','high_end',1,1280,100,1180,300,'wechat','胡语','胡语','',20,'测试订单','active'),
('YM202605140106','2026-05-14','2026-05','龙泉1店','刘姐','13800000006','逆龄炮','high_end',1,880,0,880,220,'cash','琳娜','胡语','',15,'测试订单','active'),
('YM202605130107','2026-05-13','2026-05','龙泉1店','陈姐','13800000007','肩颈调理','body',2,796,96,700,240,'wechat','胡语','琳娜','',16,'测试订单','active'),
('YM202605120108','2026-05-12','2026-05','龙泉1店','杨姐','13800000008','臀疗','body',1,680,0,680,180,'package','琳娜','胡语','',15,'测试订单','active'),
('YM202605110109','2026-05-11','2026-05','龙泉1店','何姐','13800000009','面部基础护理','face',1,298,0,298,90,'wechat','胡语','琳娜','',3,'测试订单','active'),
('YM202605100110','2026-05-10','2026-05','龙泉1店','唐姐','13800000010','骨龄抗衰','high_end',1,1280,180,1100,300,'cash','琳娜','胡语','',20,'测试订单','active'),
('YM202605180201','2026-05-18','2026-05','龙泉2店','宋姐','13800000011','肩颈调理','body',1,398,0,398,120,'wechat','李继','李继','',8,'测试订单','active'),
('YM202605170202','2026-05-17','2026-05','龙泉2店','孙姐','13800000012','臀疗','body',1,680,80,600,180,'cash','李继','李继','',15,'测试订单','active'),
('YM202605160203','2026-05-16','2026-05','龙泉2店','吴姐','13800000013','肝胆排毒','body',1,980,0,980,260,'alipay','李继','李继','',15,'测试订单','active'),
('YM202605150204','2026-05-15','2026-05','龙泉2店','郑姐','13800000014','面部基础护理','face',2,596,96,500,160,'card','李继','李继','',6,'测试订单','active'),
('YM202605140205','2026-05-14','2026-05','龙泉2店','冯姐','13800000015','骨龄抗衰','high_end',1,1280,100,1180,300,'wechat','李继','李继','',20,'测试订单','active'),
('YM202605130206','2026-05-13','2026-05','龙泉2店','蒋姐','13800000016','逆龄炮','high_end',1,880,0,880,220,'cash','李继','李继','',15,'测试订单','active'),
('YM202605120207','2026-05-12','2026-05','龙泉2店','谢姐','13800000017','肩颈调理','body',2,796,96,700,240,'wechat','李继','李继','',16,'测试订单','active'),
('YM202605110208','2026-05-11','2026-05','龙泉2店','邓姐','13800000018','臀疗','body',1,680,0,680,180,'package','李继','李继','',15,'测试订单','active'),
('YM202605100209','2026-05-10','2026-05','龙泉2店','沈姐','13800000019','面部基础护理','face',1,298,0,298,90,'wechat','李继','李继','',3,'测试订单','active'),
('YM202605090210','2026-05-09','2026-05','龙泉2店','马姐','13800000020','骨龄抗衰','high_end',1,1280,180,1100,300,'cash','李继','李继','',20,'测试订单','active'),
('YM202605180301','2026-05-18','2026-05','龙泉金龙店','韩姐','13800000021','肩颈调理','body',1,398,0,398,120,'wechat','王红','王红','',8,'测试订单','active'),
('YM202605170302','2026-05-17','2026-05','龙泉金龙店','潘姐','13800000022','臀疗','body',1,680,80,600,180,'cash','王红','王红','',15,'测试订单','active'),
('YM202605160303','2026-05-16','2026-05','龙泉金龙店','董姐','13800000023','肝胆排毒','body',1,980,0,980,260,'alipay','王红','王红','',15,'测试订单','active'),
('YM202605150304','2026-05-15','2026-05','龙泉金龙店','魏姐','13800000024','面部基础护理','face',2,596,96,500,160,'card','王红','王红','',6,'测试订单','active'),
('YM202605140305','2026-05-14','2026-05','龙泉金龙店','袁姐','13800000025','骨龄抗衰','high_end',1,1280,100,1180,300,'wechat','王红','王红','',20,'测试订单','active'),
('YM202605130306','2026-05-13','2026-05','龙泉金龙店','罗姐','13800000026','逆龄炮','high_end',1,880,0,880,220,'cash','王红','王红','',15,'测试订单','active'),
('YM202605120307','2026-05-12','2026-05','龙泉金龙店','梁姐','13800000027','肩颈调理','body',2,796,96,700,240,'wechat','王红','王红','',16,'测试订单','active'),
('YM202605110308','2026-05-11','2026-05','龙泉金龙店','许姐','13800000028','臀疗','body',1,680,0,680,180,'package','王红','王红','',15,'测试订单','active'),
('YM202605100309','2026-05-10','2026-05','龙泉金龙店','田姐','13800000029','面部基础护理','face',1,298,0,298,90,'wechat','王红','王红','',3,'测试订单','active'),
('YM202605090310','2026-05-09','2026-05','龙泉金龙店','杜姐','13800000030','骨龄抗衰','high_end',1,1280,180,1100,300,'cash','王红','王红','',20,'测试订单','active'),
('YM202605180401','2026-05-18','2026-05','郫县1店','叶姐','13800000031','肩颈调理','body',1,398,0,398,120,'wechat','黄云','黄云','',8,'测试订单','active'),
('YM202605170402','2026-05-17','2026-05','郫县1店','余姐','13800000032','臀疗','body',1,680,80,600,180,'cash','黄云','黄云','',15,'测试订单','active'),
('YM202605160403','2026-05-16','2026-05','郫县1店','夏姐','13800000033','肝胆排毒','body',1,980,0,980,260,'alipay','黄云','黄云','',15,'测试订单','active'),
('YM202605150404','2026-05-15','2026-05','郫县1店','钟姐','13800000034','面部基础护理','face',2,596,96,500,160,'card','黄云','黄云','',6,'测试订单','active'),
('YM202605140405','2026-05-14','2026-05','郫县1店','汪姐','13800000035','骨龄抗衰','high_end',1,1280,100,1180,300,'wechat','黄云','黄云','',20,'测试订单','active'),
('YM202605130406','2026-05-13','2026-05','郫县1店','卢姐','13800000036','逆龄炮','high_end',1,880,0,880,220,'cash','黄云','黄云','',15,'测试订单','active'),
('YM202605120407','2026-05-12','2026-05','郫县1店','邱姐','13800000037','肩颈调理','body',2,796,96,700,240,'wechat','黄云','黄云','',16,'测试订单','active'),
('YM202605110408','2026-05-11','2026-05','郫县1店','孟姐','13800000038','臀疗','body',1,680,0,680,180,'package','黄云','黄云','',15,'测试订单','active'),
('YM202605100409','2026-05-10','2026-05','郫县1店','白姐','13800000039','面部基础护理','face',1,298,0,298,90,'wechat','黄云','黄云','',3,'测试订单','active'),
('YM202605090410','2026-05-09','2026-05','郫县1店','秦姐','13800000040','骨龄抗衰','high_end',1,1280,180,1100,300,'cash','黄云','黄云','',20,'测试订单','active')
on conflict (order_no) do nothing;

commit;
