begin;

create table if not exists public.employee_performance_reports (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  employee text,
  arrivals numeric default 0,
  service_sales numeric default 0,
  consume_sales numeric default 0,
  cash_sales numeric default 0,
  new_customers numeric default 0,
  repeat_customers numeric default 0,
  upsell_amount numeric default 0,
  total_sales numeric default 0,
  unit_price numeric default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.employee_performance_reports
  add column if not exists date date,
  add column if not exists store text,
  add column if not exists employee text,
  add column if not exists arrivals numeric default 0,
  add column if not exists service_sales numeric default 0,
  add column if not exists consume_sales numeric default 0,
  add column if not exists cash_sales numeric default 0,
  add column if not exists new_customers numeric default 0,
  add column if not exists repeat_customers numeric default 0,
  add column if not exists upsell_amount numeric default 0,
  add column if not exists total_sales numeric default 0,
  add column if not exists unit_price numeric default 0,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_performance_reports'
      and column_name = 'report_date'
  ) then
    execute 'update public.employee_performance_reports set date = coalesce(date, report_date)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_performance_reports'
      and column_name = 'arrivals_count'
  ) then
    execute 'update public.employee_performance_reports set arrivals = coalesce(nullif(arrivals, 0), arrivals_count)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_performance_reports'
      and column_name = 'manual_performance'
  ) then
    execute 'update public.employee_performance_reports set service_sales = coalesce(nullif(service_sales, 0), manual_performance)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_performance_reports'
      and column_name = 'consumption_performance'
  ) then
    execute 'update public.employee_performance_reports set consume_sales = coalesce(nullif(consume_sales, 0), consumption_performance)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_performance_reports'
      and column_name = 'cash_performance'
  ) then
    execute 'update public.employee_performance_reports set cash_sales = coalesce(nullif(cash_sales, 0), cash_performance)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_performance_reports'
      and column_name = 'new_customer_count'
  ) then
    execute 'update public.employee_performance_reports set new_customers = coalesce(nullif(new_customers, 0), new_customer_count)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_performance_reports'
      and column_name = 'repeat_customer_count'
  ) then
    execute 'update public.employee_performance_reports set repeat_customers = coalesce(nullif(repeat_customers, 0), repeat_customer_count)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_performance_reports'
      and column_name = 'upsell_amount'
  ) then
    execute 'update public.employee_performance_reports set upsell_amount = coalesce(upsell_amount, upsell_amount)';
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'employee_performance_reports'
      and column_name = 'upgrade_sales'
  ) then
    execute 'update public.employee_performance_reports set upsell_amount = coalesce(nullif(upsell_amount, 0), upgrade_sales)';
  end if;
end $$;

update public.employee_performance_reports
set
  total_sales =
    coalesce(service_sales, 0)
    + coalesce(consume_sales, 0)
    + coalesce(cash_sales, 0)
    + coalesce(upsell_amount, 0),
  unit_price = case
    when coalesce(arrivals, 0) > 0 then (
      coalesce(service_sales, 0)
      + coalesce(consume_sales, 0)
      + coalesce(cash_sales, 0)
      + coalesce(upsell_amount, 0)
    ) / arrivals
    else 0
  end;

create index if not exists idx_employee_performance_reports_date
on public.employee_performance_reports (date);

create index if not exists idx_employee_performance_reports_store
on public.employee_performance_reports (store);

create index if not exists idx_employee_performance_reports_employee
on public.employee_performance_reports (employee);

create index if not exists idx_employee_performance_reports_created_at
on public.employee_performance_reports (created_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_employee_performance_reports_updated_at
on public.employee_performance_reports;

create trigger trg_employee_performance_reports_updated_at
before update on public.employee_performance_reports
for each row
execute function public.set_updated_at();

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where user_id = auth.uid()::text
  limit 1
$$;

create or replace function public.current_profile_store()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select store
  from public.profiles
  where user_id = auth.uid()::text
  limit 1
$$;

create or replace function public.current_profile_name()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select name
  from public.profiles
  where user_id = auth.uid()::text
  limit 1
$$;

alter table public.employee_performance_reports enable row level security;

drop policy if exists employee_performance_reports_select_scope
on public.employee_performance_reports;

create policy employee_performance_reports_select_scope
on public.employee_performance_reports
for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
  or (
    public.current_profile_role() = 'beautician'
    and employee = public.current_profile_name()
  )
);

drop policy if exists employee_performance_reports_insert_scope
on public.employee_performance_reports;

create policy employee_performance_reports_insert_scope
on public.employee_performance_reports
for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
  or (
    public.current_profile_role() = 'beautician'
    and store = public.current_profile_store()
    and employee = public.current_profile_name()
  )
);

drop policy if exists employee_performance_reports_update_scope
on public.employee_performance_reports;

create policy employee_performance_reports_update_scope
on public.employee_performance_reports
for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
  or (
    public.current_profile_role() = 'beautician'
    and employee = public.current_profile_name()
  )
)
with check (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
  or (
    public.current_profile_role() = 'beautician'
    and store = public.current_profile_store()
    and employee = public.current_profile_name()
  )
);

drop policy if exists employee_performance_reports_delete_scope
on public.employee_performance_reports;

create policy employee_performance_reports_delete_scope
on public.employee_performance_reports
for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
  or (
    public.current_profile_role() = 'beautician'
    and employee = public.current_profile_name()
  )
);

commit;
