-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 修复 followups.customer_id 类型
-- customers.id 是 int/bigint，因此 followups.customer_id 必须是 bigint，不能是 uuid。
-- 说明：如果线上 customer_id 当前是 uuid，本脚本会删除该 uuid 列并重建为 bigint。

create table if not exists public.followups (
  id bigint generated by default as identity primary key
);

do $$
declare
  current_type text;
begin
  select data_type
  into current_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'followups'
    and column_name = 'customer_id';

  if current_type is null then
    alter table public.followups
      add column customer_id bigint;
  elsif current_type <> 'bigint' then
    alter table public.followups
      drop column customer_id;

    alter table public.followups
      add column customer_id bigint;
  end if;
end;
$$;

alter table public.followups
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists owner text,
  add column if not exists method text,
  add column if not exists content text,
  add column if not exists feedback text,
  add column if not exists issue_type text,
  add column if not exists has_appointment boolean not null default false,
  add column if not exists appointment_time date,
  add column if not exists has_deal boolean not null default false,
  add column if not exists deal_amount numeric not null default 0,
  add column if not exists next_follow_time date,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
