-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase part2a_1
-- 执行顺序：part2a_1 -> part2a_2 -> part2a_3
-- 本段：创建员工表 staff

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  phone text,
  store text,
  role text,
  today_followups integer not null default 0,
  today_appointments integer not null default 0,
  today_visits integer not null default 0,
  today_deals integer not null default 0,
  today_revenue numeric not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
