-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase part2a_3
-- 执行顺序：part2a_1 -> part2a_2 -> part2a_3
-- 本段：补齐员工每日数据字段

create table if not exists public.staff (
  id bigint generated by default as identity primary key
);

alter table public.staff
  add column if not exists today_followups integer not null default 0,
  add column if not exists today_appointments integer not null default 0,
  add column if not exists today_visits integer not null default 0,
  add column if not exists today_deals integer not null default 0,
  add column if not exists today_revenue numeric not null default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
