-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase part2a_2
-- 执行顺序：part2a_1 -> part2a_2 -> part2a_3
-- 本段：补齐员工基础字段

create table if not exists public.staff (
  id bigint generated by default as identity primary key
);

alter table public.staff
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text;
