-- 雅美靓颜门店管理系统最终数据库结构
-- 只保留当前系统真实使用字段。

begin;

create table if not exists public.stores (
  id bigint generated always as identity primary key,
  name text,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id text,
  name text,
  role text,
  store text,
  created_at timestamptz default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  age numeric,
  birthday date,
  store text,
  owner text,
  level text,
  last_visit date,
  follow_status text,
  last_follow_result text,
  last_follow_time date,
  next_follow_time date,
  follow_note text,
  today_task_completed_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  store text,
  role text,
  note text,
  base_salary numeric default 0,
  social_security_allowance numeric default 0,
  full_attendance_bonus numeric default 0,
  seniority_salary numeric default 0,
  entry_date date,
  is_active boolean default true,
  is_technical_department boolean default false,
  salary_plan_type text,
  today_followups numeric default 0,
  today_appointments numeric default 0,
  today_arrivals numeric default 0,
  today_deals numeric default 0,
  today_sales numeric default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.employee_daily_stats (
  id bigint generated by default as identity primary key,
  date date,
  employee_id bigint,
  employee_name text,
  phone text,
  store text,
  role text,
  followups numeric default 0,
  appointments numeric default 0,
  arrivals numeric default 0,
  deals numeric default 0,
  sales numeric default 0,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.employee_performance_reports (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  employee text,
  arrivals numeric default 0,
  service_sales numeric default 0,
  consume_sales numeric default 0,
  cash_sales numeric default 0,
  new_customers numeric default 0,
  repeat_customers numeric default 0,
  upsell_amount numeric default 0,
  total_sales numeric default 0,
  unit_price numeric default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.store_targets (
  id bigint generated by default as identity primary key,
  month text,
  store text,
  monthly_target numeric default 0,
  daily_target numeric default 0,
  current_sales numeric default 0,
  completion_rate numeric default 0,
  remaining_amount numeric default 0,
  created_at timestamptz default now()
);

create table if not exists public.project_commission_settings (
  id bigint generated by default as identity primary key,
  project_name text,
  category text,
  manual_commission numeric default 0,
  duration_minutes numeric,
  unit text default '次',
  is_active boolean default true,
  remark text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.performance_records (
  id bigint generated by default as identity primary key,
  date date,
  month text,
  store_id bigint,
  store_name text,
  customer_id bigint,
  customer_name text,
  project_id bigint,
  project_name text,
  project_category text,
  amount numeric default 0,
  consume_amount numeric default 0,
  payment_type text,
  service_employee_id bigint,
  service_employee_name text,
  sales_employee_id bigint,
  sales_employee_name text,
  consultant_id bigint,
  consultant_name text,
  quantity numeric default 1,
  manual_commission_amount numeric default 0,
  remark text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.cashier_orders (
  id bigint generated by default as identity primary key,
  order_no text,
  date date,
  month text,
  store_id bigint,
  store_name text,
  customer_id bigint,
  customer_name text,
  customer_phone text,
  project_id bigint,
  project_name text,
  project_category text,
  quantity numeric default 1,
  original_amount numeric default 0,
  discount_amount numeric default 0,
  actual_amount numeric default 0,
  consume_amount numeric default 0,
  payment_type text,
  service_employee_id bigint,
  service_employee_name text,
  sales_employee_id bigint,
  sales_employee_name text,
  consultant_id bigint,
  consultant_name text,
  manual_commission_amount numeric default 0,
  remark text,
  status text default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.cashier_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.cashier_orders(id) on delete cascade,
  project_id bigint,
  project_name text,
  project_category text,
  quantity numeric default 1,
  original_amount numeric default 0,
  discount_amount numeric default 0,
  actual_amount numeric default 0,
  consume_amount numeric default 0,
  manual_commission numeric default 0,
  manual_commission_amount numeric default 0,
  duration_minutes numeric,
  created_at timestamptz default now()
);

create table if not exists public.followups (
  id bigint generated by default as identity primary key,
  customer_id bigint,
  customer_name text,
  customer_phone text,
  store text,
  owner text,
  method text,
  content text,
  feedback text,
  issue_type text,
  has_appointment boolean default false,
  appointment_time date,
  has_deal boolean default false,
  deal_amount numeric default 0,
  next_follow_time date,
  created_at timestamptz default now()
);

create table if not exists public.daily_reviews (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  invite_rate numeric default 0,
  appointment_rate numeric default 0,
  arrival_rate numeric default 0,
  deal_rate numeric default 0,
  deal_amount numeric default 0,
  unfinished_reason text,
  tomorrow_action text,
  created_at timestamptz default now()
);

alter table public.stores
  add column if not exists name text,
  add column if not exists created_at timestamptz default now();

alter table public.profiles
  add column if not exists user_id text,
  add column if not exists name text,
  add column if not exists role text,
  add column if not exists store text,
  add column if not exists created_at timestamptz default now();

alter table public.customers
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists age numeric,
  add column if not exists birthday date,
  add column if not exists store text,
  add column if not exists owner text,
  add column if not exists level text,
  add column if not exists last_visit date,
  add column if not exists follow_status text,
  add column if not exists last_follow_result text,
  add column if not exists last_follow_time date,
  add column if not exists next_follow_time date,
  add column if not exists follow_note text,
  add column if not exists today_task_completed_at timestamptz,
  add column if not exists created_at timestamptz default now();

alter table public.employees
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists note text,
  add column if not exists base_salary numeric default 0,
  add column if not exists social_security_allowance numeric default 0,
  add column if not exists full_attendance_bonus numeric default 0,
  add column if not exists seniority_salary numeric default 0,
  add column if not exists entry_date date,
  add column if not exists is_active boolean default true,
  add column if not exists is_technical_department boolean default false,
  add column if not exists salary_plan_type text,
  add column if not exists today_followups numeric default 0,
  add column if not exists today_appointments numeric default 0,
  add column if not exists today_arrivals numeric default 0,
  add column if not exists today_deals numeric default 0,
  add column if not exists today_sales numeric default 0,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.employee_daily_stats
  add column if not exists date date,
  add column if not exists employee_id bigint,
  add column if not exists employee_name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists followups numeric default 0,
  add column if not exists appointments numeric default 0,
  add column if not exists arrivals numeric default 0,
  add column if not exists deals numeric default 0,
  add column if not exists sales numeric default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.employee_performance_reports
  add column if not exists date date,
  add column if not exists store text,
  add column if not exists employee text,
  add column if not exists arrivals numeric default 0,
  add column if not exists service_sales numeric default 0,
  add column if not exists consume_sales numeric default 0,
  add column if not exists cash_sales numeric default 0,
  add column if not exists new_customers numeric default 0,
  add column if not exists repeat_customers numeric default 0,
  add column if not exists upsell_amount numeric default 0,
  add column if not exists total_sales numeric default 0,
  add column if not exists unit_price numeric default 0,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.store_targets
  add column if not exists month text,
  add column if not exists store text,
  add column if not exists monthly_target numeric default 0,
  add column if not exists daily_target numeric default 0,
  add column if not exists current_sales numeric default 0,
  add column if not exists completion_rate numeric default 0,
  add column if not exists remaining_amount numeric default 0,
  add column if not exists created_at timestamptz default now();

alter table public.project_commission_settings
  add column if not exists project_name text,
  add column if not exists category text,
  add column if not exists manual_commission numeric default 0,
  add column if not exists duration_minutes numeric,
  add column if not exists unit text default '次',
  add column if not exists is_active boolean default true,
  add column if not exists remark text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.performance_records
  add column if not exists date date,
  add column if not exists month text,
  add column if not exists store_id bigint,
  add column if not exists store_name text,
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists project_id bigint,
  add column if not exists project_name text,
  add column if not exists project_category text,
  add column if not exists amount numeric default 0,
  add column if not exists consume_amount numeric default 0,
  add column if not exists payment_type text,
  add column if not exists service_employee_id bigint,
  add column if not exists service_employee_name text,
  add column if not exists sales_employee_id bigint,
  add column if not exists sales_employee_name text,
  add column if not exists consultant_id bigint,
  add column if not exists consultant_name text,
  add column if not exists quantity numeric default 1,
  add column if not exists manual_commission_amount numeric default 0,
  add column if not exists remark text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.cashier_orders
  add column if not exists order_no text,
  add column if not exists date date,
  add column if not exists month text,
  add column if not exists store_id bigint,
  add column if not exists store_name text,
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists project_id bigint,
  add column if not exists project_name text,
  add column if not exists project_category text,
  add column if not exists quantity numeric default 1,
  add column if not exists original_amount numeric default 0,
  add column if not exists discount_amount numeric default 0,
  add column if not exists actual_amount numeric default 0,
  add column if not exists consume_amount numeric default 0,
  add column if not exists payment_type text,
  add column if not exists service_employee_id bigint,
  add column if not exists service_employee_name text,
  add column if not exists sales_employee_id bigint,
  add column if not exists sales_employee_name text,
  add column if not exists consultant_id bigint,
  add column if not exists consultant_name text,
  add column if not exists manual_commission_amount numeric default 0,
  add column if not exists remark text,
  add column if not exists status text default 'active',
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.cashier_order_items
  add column if not exists order_id bigint,
  add column if not exists project_id bigint,
  add column if not exists project_name text,
  add column if not exists project_category text,
  add column if not exists quantity numeric default 1,
  add column if not exists original_amount numeric default 0,
  add column if not exists discount_amount numeric default 0,
  add column if not exists actual_amount numeric default 0,
  add column if not exists consume_amount numeric default 0,
  add column if not exists manual_commission numeric default 0,
  add column if not exists manual_commission_amount numeric default 0,
  add column if not exists duration_minutes numeric,
  add column if not exists created_at timestamptz default now();

alter table public.followups
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists store text,
  add column if not exists owner text,
  add column if not exists method text,
  add column if not exists content text,
  add column if not exists feedback text,
  add column if not exists issue_type text,
  add column if not exists has_appointment boolean default false,
  add column if not exists appointment_time date,
  add column if not exists has_deal boolean default false,
  add column if not exists deal_amount numeric default 0,
  add column if not exists next_follow_time date,
  add column if not exists created_at timestamptz default now();

alter table public.daily_reviews
  add column if not exists date date,
  add column if not exists store text,
  add column if not exists invite_rate numeric default 0,
  add column if not exists appointment_rate numeric default 0,
  add column if not exists arrival_rate numeric default 0,
  add column if not exists deal_rate numeric default 0,
  add column if not exists deal_amount numeric default 0,
  add column if not exists unfinished_reason text,
  add column if not exists tomorrow_action text,
  add column if not exists created_at timestamptz default now();

alter table public.customers
  drop column if exists store_id,
  drop column if exists project,
  drop column if exists spend,
  drop column if exists remaining,
  drop column if exists status,
  drop column if exists note,
  drop column if exists beautician,
  drop column if exists staff_name,
  drop column if exists employee_name,
  drop column if exists owner_name,
  drop column if exists responsible_staff,
  drop column if exists recent_visit;

alter table public.employees
  drop column if exists today_visits,
  drop column if exists today_revenue,
  drop column if exists "todaySales",
  drop column if exists sales,
  drop column if exists today_amount,
  drop column if exists position;

alter table public.followups
  drop column if exists date;

update public.profiles
set role = case role
  when '老板' then 'boss'
  when '店长' then 'manager'
  when '美容师' then 'beautician'
  else role
end
where role in ('老板', '店长', '美容师');

update public.employees
set role = case role
  when '老板' then 'boss'
  when '店长' then 'manager'
  when '美容师' then 'beautician'
  else role
end
where role in ('老板', '店长', '美容师');

create index if not exists idx_stores_name on public.stores (name);
create index if not exists idx_profiles_user_id on public.profiles (user_id);
create index if not exists idx_profiles_role on public.profiles (role);
create index if not exists idx_profiles_store on public.profiles (store);
create index if not exists idx_customers_store on public.customers (store);
create index if not exists idx_customers_owner on public.customers (owner);
create index if not exists idx_customers_last_visit on public.customers (last_visit);
drop index if exists public.idx_customers_phone;
drop index if exists public.idx_customers_phone_unique;
update public.customers
set phone = null
where phone = '';
delete from public.customers a
using public.customers b
where a.phone is not null
  and a.phone = b.phone
  and a.id < b.id;
create unique index if not exists idx_customers_phone_unique on public.customers (phone);
create index if not exists idx_employees_store on public.employees (store);
create index if not exists idx_employees_role on public.employees (role);
create index if not exists idx_employees_name on public.employees (name);
create unique index if not exists idx_employee_daily_stats_date_employee_id on public.employee_daily_stats (date, employee_id);
create index if not exists idx_employee_daily_stats_date on public.employee_daily_stats (date);
create index if not exists idx_employee_daily_stats_store on public.employee_daily_stats (store);
create index if not exists idx_employee_daily_stats_employee_id on public.employee_daily_stats (employee_id);
create index if not exists idx_employee_performance_reports_date on public.employee_performance_reports (date);
create index if not exists idx_employee_performance_reports_store on public.employee_performance_reports (store);
create index if not exists idx_employee_performance_reports_employee on public.employee_performance_reports (employee);
create unique index if not exists idx_store_targets_month_store on public.store_targets (month, store);
create index if not exists idx_store_targets_store on public.store_targets (store);
create index if not exists idx_store_targets_month on public.store_targets (month);
create index if not exists idx_project_commission_settings_project_name on public.project_commission_settings (project_name);
create unique index if not exists idx_project_commission_settings_project_name_unique on public.project_commission_settings (project_name);
create index if not exists idx_project_commission_settings_category on public.project_commission_settings (category);
create index if not exists idx_performance_records_month on public.performance_records (month);
create index if not exists idx_performance_records_date on public.performance_records (date);
create index if not exists idx_performance_records_store_name on public.performance_records (store_name);
create index if not exists idx_performance_records_service_employee_name on public.performance_records (service_employee_name);
create index if not exists idx_performance_records_sales_employee_name on public.performance_records (sales_employee_name);
create unique index if not exists idx_cashier_orders_order_no_unique on public.cashier_orders (order_no);
create index if not exists idx_cashier_orders_month on public.cashier_orders (month);
create index if not exists idx_cashier_orders_date on public.cashier_orders (date);
create index if not exists idx_cashier_orders_store_name on public.cashier_orders (store_name);
create index if not exists idx_cashier_orders_service_employee_name on public.cashier_orders (service_employee_name);
create index if not exists idx_cashier_orders_sales_employee_name on public.cashier_orders (sales_employee_name);
create index if not exists idx_cashier_orders_consultant_name on public.cashier_orders (consultant_name);
create index if not exists idx_cashier_orders_status on public.cashier_orders (status);
create index if not exists idx_cashier_order_items_order_id on public.cashier_order_items (order_id);
create index if not exists idx_cashier_order_items_project_name on public.cashier_order_items (project_name);
create index if not exists idx_followups_store on public.followups (store);
create index if not exists idx_followups_owner on public.followups (owner);
create index if not exists idx_followups_customer_id on public.followups (customer_id);
create index if not exists idx_followups_created_at on public.followups (created_at);
create index if not exists idx_daily_reviews_store on public.daily_reviews (store);
create index if not exists idx_daily_reviews_date on public.daily_reviews (date);
create index if not exists idx_daily_reviews_created_at on public.daily_reviews (created_at);

insert into public.project_commission_settings (project_name, category, manual_commission, duration_minutes, unit, is_active, remark)
values
('面部基础护理', 'face', 3, 60, '次', true, ''),
('眼八宝', 'face', 3, 30, '次', true, ''),
('面部香薰', 'face', 5, 60, '次', true, ''),
('颈护', 'body', 3, 30, '次', true, ''),
('肩颈调理', 'body', 8, 60, '次', true, ''),
('胸部保养', 'body', 8, 45, '次', true, ''),
('卵巢保养', 'body', 8, 45, '次', true, ''),
('肾保', 'body', 8, 45, '次', true, ''),
('肝胆排毒', 'body', 15, 90, '次', true, ''),
('淋巴', 'body', 8, 45, '次', true, ''),
('腿部保养', 'body', 8, 45, '次', true, ''),
('臀疗', 'body', 15, 45, '次', true, ''),
('头疗', 'body', 3, 45, '次', true, ''),
('艾灸', 'moxibustion', 0.5, null, '个', true, ''),
('泥灸', 'moxibustion', 1, null, '张', true, ''),
('贝罗娜', 'high_end', 15, null, '次', true, ''),
('中胚', 'high_end', 15, null, '次', true, ''),
('祛木', 'high_end', 15, null, '次', true, ''),
('私密SAP', 'high_end', 20, null, '次', true, ''),
('苗药', 'high_end', 8, null, '次', true, ''),
('童颜抗衰仪', 'high_end', 15, null, '次', true, ''),
('魔术刀', 'high_end', 15, 40, '次', true, '局部15元'),
('骨龄抗衰', 'high_end', 20, 40, '次', true, ''),
('逆龄炮', 'high_end', 15, 30, '次', true, '')
on conflict (project_name) do nothing;

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select case
    when role = 'admin' then 'boss'
    when role in ('employee', 'consultant', 'technical_teacher') then 'beautician'
    when role = 'regional_manager' then 'boss'
    else role
  end from public.profiles where user_id = auth.uid()::text limit 1
$$;

create or replace function public.current_profile_store()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select store from public.profiles where user_id = auth.uid()::text limit 1
$$;

create or replace function public.current_profile_name()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select name from public.profiles where user_id = auth.uid()::text limit 1
$$;

alter table public.stores enable row level security;
alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.employees enable row level security;
alter table public.employee_daily_stats enable row level security;
alter table public.employee_performance_reports enable row level security;
alter table public.store_targets enable row level security;
alter table public.project_commission_settings enable row level security;
alter table public.performance_records enable row level security;
alter table public.cashier_orders enable row level security;
alter table public.cashier_order_items enable row level security;
alter table public.followups enable row level security;
alter table public.daily_reviews enable row level security;

drop policy if exists stores_authenticated_select on public.stores;
create policy stores_authenticated_select
on public.stores for select
to authenticated
using (true);

drop policy if exists profiles_select_scope on public.profiles;
create policy profiles_select_scope
on public.profiles for select
to authenticated
using (
  user_id = auth.uid()::text
  or public.current_profile_role() = 'boss'
);

drop policy if exists profiles_update_self_or_boss on public.profiles;
create policy profiles_update_self_or_boss
on public.profiles for update
to authenticated
using (
  user_id = auth.uid()::text
  or public.current_profile_role() = 'boss'
)
with check (
  user_id = auth.uid()::text
  or public.current_profile_role() = 'boss'
);

drop policy if exists customers_select_scope on public.customers;
create policy customers_select_scope
on public.customers for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
);

drop policy if exists customers_insert_scope on public.customers;
create policy customers_insert_scope
on public.customers for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists customers_update_scope on public.customers;
create policy customers_update_scope
on public.customers for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and owner = public.current_profile_name())
);

drop policy if exists customers_delete_scope on public.customers;
create policy customers_delete_scope
on public.customers for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employees_select_scope on public.employees;
create policy employees_select_scope
on public.employees for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and name = public.current_profile_name())
);

drop policy if exists employees_insert_scope on public.employees;
create policy employees_insert_scope
on public.employees for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
);

drop policy if exists employees_update_scope on public.employees;
create policy employees_update_scope
on public.employees for update
to authenticated
using (
  public.current_profile_role() = 'boss'
)
with check (
  public.current_profile_role() = 'boss'
);

drop policy if exists employees_delete_scope on public.employees;
create policy employees_delete_scope
on public.employees for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
);

drop policy if exists employee_daily_stats_select_scope on public.employee_daily_stats;
create policy employee_daily_stats_select_scope
on public.employee_daily_stats for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and employee_name = public.current_profile_name())
);

drop policy if exists employee_daily_stats_insert_scope on public.employee_daily_stats;
create policy employee_daily_stats_insert_scope
on public.employee_daily_stats for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employee_daily_stats_update_scope on public.employee_daily_stats;
create policy employee_daily_stats_update_scope
on public.employee_daily_stats for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employee_performance_reports_select_scope on public.employee_performance_reports;
create policy employee_performance_reports_select_scope
on public.employee_performance_reports for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and employee = public.current_profile_name())
);

drop policy if exists employee_performance_reports_insert_scope on public.employee_performance_reports;
create policy employee_performance_reports_insert_scope
on public.employee_performance_reports for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and employee = public.current_profile_name())
);

drop policy if exists employee_performance_reports_update_scope on public.employee_performance_reports;
create policy employee_performance_reports_update_scope
on public.employee_performance_reports for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and employee = public.current_profile_name())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and employee = public.current_profile_name())
);

drop policy if exists employee_performance_reports_delete_scope on public.employee_performance_reports;
create policy employee_performance_reports_delete_scope
on public.employee_performance_reports for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and employee = public.current_profile_name())
);

drop policy if exists store_targets_select_scope on public.store_targets;
create policy store_targets_select_scope
on public.store_targets for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists store_targets_insert_scope on public.store_targets;
create policy store_targets_insert_scope
on public.store_targets for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists store_targets_update_scope on public.store_targets;
create policy store_targets_update_scope
on public.store_targets for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists store_targets_delete_scope on public.store_targets;
create policy store_targets_delete_scope
on public.store_targets for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists project_commission_settings_select_scope on public.project_commission_settings;
create policy project_commission_settings_select_scope
on public.project_commission_settings for select
to authenticated
using (true);

drop policy if exists project_commission_settings_insert_scope on public.project_commission_settings;
create policy project_commission_settings_insert_scope
on public.project_commission_settings for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
);

drop policy if exists project_commission_settings_update_scope on public.project_commission_settings;
create policy project_commission_settings_update_scope
on public.project_commission_settings for update
to authenticated
using (
  public.current_profile_role() = 'boss'
)
with check (
  public.current_profile_role() = 'boss'
);

drop policy if exists performance_records_select_scope on public.performance_records;
create policy performance_records_select_scope
on public.performance_records for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and (service_employee_name = public.current_profile_name() or sales_employee_name = public.current_profile_name()))
);

drop policy if exists performance_records_insert_scope on public.performance_records;
create policy performance_records_insert_scope
on public.performance_records for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store_name = public.current_profile_store() and (service_employee_name = public.current_profile_name() or sales_employee_name = public.current_profile_name()))
);

drop policy if exists performance_records_update_scope on public.performance_records;
create policy performance_records_update_scope
on public.performance_records for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and (service_employee_name = public.current_profile_name() or sales_employee_name = public.current_profile_name()))
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store_name = public.current_profile_store() and (service_employee_name = public.current_profile_name() or sales_employee_name = public.current_profile_name()))
);

drop policy if exists performance_records_delete_scope on public.performance_records;
create policy performance_records_delete_scope
on public.performance_records for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
);

drop policy if exists cashier_orders_select_scope on public.cashier_orders;
create policy cashier_orders_select_scope
on public.cashier_orders for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and (
    service_employee_name = public.current_profile_name()
    or sales_employee_name = public.current_profile_name()
    or consultant_name = public.current_profile_name()
  ))
);

drop policy if exists cashier_orders_insert_scope on public.cashier_orders;
create policy cashier_orders_insert_scope
on public.cashier_orders for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
);

drop policy if exists cashier_orders_update_scope on public.cashier_orders;
create policy cashier_orders_update_scope
on public.cashier_orders for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store_name = public.current_profile_store())
);

drop policy if exists cashier_orders_delete_scope on public.cashier_orders;
create policy cashier_orders_delete_scope
on public.cashier_orders for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
);

drop policy if exists cashier_order_items_select_scope on public.cashier_order_items;
create policy cashier_order_items_select_scope
on public.cashier_order_items for select
to authenticated
using (
  exists (
    select 1 from public.cashier_orders o
    where o.id = cashier_order_items.order_id
      and (
        public.current_profile_role() = 'boss'
        or (public.current_profile_role() = 'manager' and o.store_name = public.current_profile_store())
        or (public.current_profile_role() = 'beautician' and (
          o.service_employee_name = public.current_profile_name()
          or o.sales_employee_name = public.current_profile_name()
          or o.consultant_name = public.current_profile_name()
        ))
      )
  )
);

drop policy if exists cashier_order_items_insert_scope on public.cashier_order_items;
create policy cashier_order_items_insert_scope
on public.cashier_order_items for insert
to authenticated
with check (
  exists (
    select 1 from public.cashier_orders o
    where o.id = cashier_order_items.order_id
      and (
        public.current_profile_role() = 'boss'
        or (public.current_profile_role() = 'manager' and o.store_name = public.current_profile_store())
      )
  )
);

drop policy if exists cashier_order_items_delete_scope on public.cashier_order_items;
create policy cashier_order_items_delete_scope
on public.cashier_order_items for delete
to authenticated
using (
  exists (
    select 1 from public.cashier_orders o
    where o.id = cashier_order_items.order_id
      and (
        public.current_profile_role() = 'boss'
        or (public.current_profile_role() = 'manager' and o.store_name = public.current_profile_store())
      )
  )
);

drop policy if exists followups_select_scope on public.followups;
create policy followups_select_scope
on public.followups for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
);

drop policy if exists followups_insert_scope on public.followups;
create policy followups_insert_scope
on public.followups for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and owner = public.current_profile_name())
);

drop policy if exists followups_update_scope on public.followups;
create policy followups_update_scope
on public.followups for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and owner = public.current_profile_name())
);

drop policy if exists followups_delete_scope on public.followups;
create policy followups_delete_scope
on public.followups for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
);

drop policy if exists daily_reviews_select_scope on public.daily_reviews;
create policy daily_reviews_select_scope
on public.daily_reviews for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists daily_reviews_insert_scope on public.daily_reviews;
create policy daily_reviews_insert_scope
on public.daily_reviews for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists daily_reviews_update_scope on public.daily_reviews;
create policy daily_reviews_update_scope
on public.daily_reviews for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists daily_reviews_delete_scope on public.daily_reviews;
create policy daily_reviews_delete_scope
on public.daily_reviews for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

commit;
