-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜门店管理系统完整 Supabase schema / migration
-- 直接复制到 Supabase SQL Editor 执行。
-- 覆盖当前前端扫描到的表：
-- profiles, stores, customers, staff, followups, daily_reviews

create extension if not exists "pgcrypto";

-- 1. 门店表：所有页面门店下拉统一读取 public.stores
create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.stores
  add column if not exists name text,
  add column if not exists created_at timestamptz not null default now();

delete from public.stores a
using public.stores b
where a.name = b.name
  and a.id > b.id;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stores_name_unique'
      and conrelid = 'public.stores'::regclass
  ) then
    alter table public.stores
      add constraint stores_name_unique unique (name);
  end if;
end;
$$;

insert into public.stores (name)
values
  ('龙泉1店'),
  ('龙泉2店'),
  ('龙泉金龙店'),
  ('郫县1店')
on conflict (name) do nothing;

-- 2. 用户资料表：前端用 user_id 读取当前登录人的角色和门店
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  name text,
  role text,
  store text,
  created_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists user_id uuid unique references auth.users(id) on delete cascade,
  add column if not exists name text,
  add column if not exists role text,
  add column if not exists store text,
  add column if not exists created_at timestamptz not null default now();

-- 3. 顾客表：对应 toCustomer/fromCustomer 和顾客档案页面
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  age integer,
  store text,
  store_id bigint,
  owner text,
  level text,
  last_visit date,
  project text,
  spend numeric not null default 0,
  remaining text,
  status text,
  note text,
  last_follow_result text,
  next_follow_time date,
  follow_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customers
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists age integer,
  add column if not exists store text,
  add column if not exists store_id bigint,
  add column if not exists owner text,
  add column if not exists level text,
  add column if not exists last_visit date,
  add column if not exists project text,
  add column if not exists spend numeric not null default 0,
  add column if not exists remaining text,
  add column if not exists status text,
  add column if not exists note text,
  add column if not exists last_follow_result text,
  add column if not exists next_follow_time date,
  add column if not exists follow_status text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 4. 员工表：前端实际使用 supabase.from('staff')
create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  phone text,
  store text,
  role text,
  today_followups integer not null default 0,
  today_appointments integer not null default 0,
  today_visits integer not null default 0,
  today_deals integer not null default 0,
  today_revenue numeric not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.staff
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists today_followups integer not null default 0,
  add column if not exists today_appointments integer not null default 0,
  add column if not exists today_visits integer not null default 0,
  add column if not exists today_deals integer not null default 0,
  add column if not exists today_revenue numeric not null default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 兼容用户提到的 employees 表：当前前端实际使用 staff，但这里也补齐 employees，方便后续迁移或外部报表使用。
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  phone text,
  store text,
  role text,
  today_followups integer not null default 0,
  today_appointments integer not null default 0,
  today_visits integer not null default 0,
  today_deals integer not null default 0,
  today_revenue numeric not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.employees
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists today_followups integer not null default 0,
  add column if not exists today_appointments integer not null default 0,
  add column if not exists today_visits integer not null default 0,
  add column if not exists today_deals integer not null default 0,
  add column if not exists today_revenue numeric not null default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 5. 跟进记录表：对应 toFollowup/fromFollowup 和跟进记录页面
create table if not exists public.followups (
  id bigint generated by default as identity primary key,
  customer_id bigint,
  customer_name text,
  customer_phone text,
  store text,
  date date,
  method text,
  owner text,
  content text,
  feedback text,
  has_appointment boolean not null default false,
  appointment_time date,
  has_deal boolean not null default false,
  deal_amount numeric not null default 0,
  next_follow_time date,
  issue_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.followups
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists store text,
  add column if not exists date date,
  add column if not exists method text,
  add column if not exists owner text,
  add column if not exists content text,
  add column if not exists feedback text,
  add column if not exists has_appointment boolean not null default false,
  add column if not exists appointment_time date,
  add column if not exists has_deal boolean not null default false,
  add column if not exists deal_amount numeric not null default 0,
  add column if not exists next_follow_time date,
  add column if not exists issue_type text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 6. 每日复盘表：对应 toReview/fromReview 和每日复盘页面
create table if not exists public.daily_reviews (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  invite_rate numeric not null default 0,
  appointment_rate numeric not null default 0,
  arrival_rate numeric not null default 0,
  deal_rate numeric not null default 0,
  deal_amount numeric not null default 0,
  unfinished_reason text,
  tomorrow_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.daily_reviews
  add column if not exists date date,
  add column if not exists store text,
  add column if not exists invite_rate numeric not null default 0,
  add column if not exists appointment_rate numeric not null default 0,
  add column if not exists arrival_rate numeric not null default 0,
  add column if not exists deal_rate numeric not null default 0,
  add column if not exists deal_amount numeric not null default 0,
  add column if not exists unfinished_reason text,
  add column if not exists tomorrow_action text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 7. 更新时间触发器
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_customers_updated_at on public.customers;
create trigger set_customers_updated_at
before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists set_staff_updated_at on public.staff;
create trigger set_staff_updated_at
before update on public.staff
for each row execute function public.set_updated_at();

drop trigger if exists set_employees_updated_at on public.employees;
create trigger set_employees_updated_at
before update on public.employees
for each row execute function public.set_updated_at();

drop trigger if exists set_followups_updated_at on public.followups;
create trigger set_followups_updated_at
before update on public.followups
for each row execute function public.set_updated_at();

drop trigger if exists set_daily_reviews_updated_at on public.daily_reviews;
create trigger set_daily_reviews_updated_at
before update on public.daily_reviews
for each row execute function public.set_updated_at();

-- 8. RLS：当前版本先保证登录用户可读写，避免页面保存失败。
alter table public.stores enable row level security;
alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.staff enable row level security;
alter table public.employees enable row level security;
alter table public.followups enable row level security;
alter table public.daily_reviews enable row level security;

drop policy if exists "stores_authenticated_all" on public.stores;
create policy "stores_authenticated_all"
on public.stores for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists "profiles_authenticated_all" on public.profiles;
create policy "profiles_authenticated_all"
on public.profiles for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists "customers_authenticated_all" on public.customers;
create policy "customers_authenticated_all"
on public.customers for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists "staff_authenticated_all" on public.staff;
create policy "staff_authenticated_all"
on public.staff for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists "employees_authenticated_all" on public.employees;
create policy "employees_authenticated_all"
on public.employees for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists "followups_authenticated_all" on public.followups;
create policy "followups_authenticated_all"
on public.followups for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

drop policy if exists "daily_reviews_authenticated_all" on public.daily_reviews;
create policy "daily_reviews_authenticated_all"
on public.daily_reviews for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

-- 9. 建议的账号资料示例
-- 创建 Supabase Auth 用户后，把 auth.users.id 填入 user_id：
-- insert into public.profiles (user_id, name, role, store)
-- values ('这里填写 auth.users.id', '王总', '老板', 'all');
-- insert into public.profiles (user_id, name, role, store)
-- values ('这里填写 auth.users.id', '龙泉1店店长', '店长', '龙泉1店');
-- insert into public.profiles (user_id, name, role, store)
-- values ('这里填写 auth.users.id', '林娜', '美容师', '龙泉1店');
