-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase schema part2b
-- 执行顺序：part2a -> part2b -> part2c
-- 本段：兼容员工表 employees、每日复盘表 daily_reviews

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  phone text,
  store text,
  role text,
  today_followups integer not null default 0,
  today_appointments integer not null default 0,
  today_visits integer not null default 0,
  today_deals integer not null default 0,
  today_revenue numeric not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.employees
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists today_followups integer not null default 0,
  add column if not exists today_appointments integer not null default 0,
  add column if not exists today_visits integer not null default 0,
  add column if not exists today_deals integer not null default 0,
  add column if not exists today_revenue numeric not null default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.daily_reviews (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  invite_rate numeric not null default 0,
  appointment_rate numeric not null default 0,
  arrival_rate numeric not null default 0,
  deal_rate numeric not null default 0,
  deal_amount numeric not null default 0,
  unfinished_reason text,
  tomorrow_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.daily_reviews
  add column if not exists date date,
  add column if not exists store text,
  add column if not exists invite_rate numeric not null default 0,
  add column if not exists appointment_rate numeric not null default 0,
  add column if not exists arrival_rate numeric not null default 0,
  add column if not exists deal_rate numeric not null default 0,
  add column if not exists deal_amount numeric not null default 0,
  add column if not exists unfinished_reason text,
  add column if not exists tomorrow_action text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
