-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase schema part2a
-- 执行顺序：part2a -> part2b -> part2c
-- 本段：员工表 staff

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  phone text,
  store text,
  role text,
  today_followups integer not null default 0,
  today_appointments integer not null default 0,
  today_visits integer not null default 0,
  today_deals integer not null default 0,
  today_revenue numeric not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.staff
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists today_followups integer not null default 0,
  add column if not exists today_appointments integer not null default 0,
  add column if not exists today_visits integer not null default 0,
  add column if not exists today_deals integer not null default 0,
  add column if not exists today_revenue numeric not null default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
