-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase schema part1
-- 执行顺序：part1 -> part2 -> part3
-- 本段：扩展、门店、用户资料、顾客表

create extension if not exists "pgcrypto";

-- 门店表：所有页面门店下拉统一读取 public.stores
create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.stores
  add column if not exists name text,
  add column if not exists created_at timestamptz not null default now();

delete from public.stores a
using public.stores b
where a.name = b.name
  and a.id > b.id;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stores_name_unique'
      and conrelid = 'public.stores'::regclass
  ) then
    alter table public.stores
      add constraint stores_name_unique unique (name);
  end if;
end;
$$;

-- 注意：stores.id 是 identity，自增主键，这里只插入 name，不手动写 id。
insert into public.stores (name)
values
  ('龙泉1店'),
  ('龙泉2店'),
  ('龙泉金龙店'),
  ('郫县1店')
on conflict (name) do nothing;

-- 用户资料表：前端用 user_id 读取当前登录人的角色和门店
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  name text,
  role text,
  store text,
  created_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists user_id uuid unique references auth.users(id) on delete cascade,
  add column if not exists name text,
  add column if not exists role text,
  add column if not exists store text,
  add column if not exists created_at timestamptz not null default now();

-- 顾客表：对应顾客档案、未到店激活、跟进记录关联
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  age integer,
  store text,
  store_id bigint,
  owner text,
  level text,
  last_visit date,
  project text,
  spend numeric not null default 0,
  remaining text,
  status text,
  note text,
  last_follow_result text,
  next_follow_time date,
  follow_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customers
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists age integer,
  add column if not exists store text,
  add column if not exists store_id bigint,
  add column if not exists owner text,
  add column if not exists level text,
  add column if not exists last_visit date,
  add column if not exists project text,
  add column if not exists spend numeric not null default 0,
  add column if not exists remaining text,
  add column if not exists status text,
  add column if not exists note text,
  add column if not exists last_follow_result text,
  add column if not exists next_follow_time date,
  add column if not exists follow_status text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
