-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase schema part1c
-- 执行顺序：part1a -> part1b -> part1c -> part2 -> part3
-- 本段：顾客表 customers

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  age integer,
  store text,
  store_id bigint,
  owner text,
  level text,
  last_visit date,
  project text,
  spend numeric not null default 0,
  remaining text,
  status text,
  note text,
  last_follow_result text,
  next_follow_time date,
  follow_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customers
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists age integer,
  add column if not exists store text,
  add column if not exists store_id bigint,
  add column if not exists owner text,
  add column if not exists level text,
  add column if not exists last_visit date,
  add column if not exists project text,
  add column if not exists spend numeric not null default 0,
  add column if not exists remaining text,
  add column if not exists status text,
  add column if not exists note text,
  add column if not exists last_follow_result text,
  add column if not exists next_follow_time date,
  add column if not exists follow_status text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
