-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase schema part1a
-- 执行顺序：part1a -> part1b -> part1c -> part2 -> part3
-- 本段：扩展、门店表、门店初始化

create extension if not exists "pgcrypto";

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.stores
  add column if not exists name text,
  add column if not exists created_at timestamptz not null default now();

delete from public.stores a
using public.stores b
where a.name = b.name
  and a.id > b.id;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stores_name_unique'
      and conrelid = 'public.stores'::regclass
  ) then
    alter table public.stores
      add constraint stores_name_unique unique (name);
  end if;
end;
$$;

insert into public.stores (name)
values
  ('龙泉1店'),
  ('龙泉2店'),
  ('龙泉金龙店'),
  ('郫县1店')
on conflict (name) do nothing;
