-- 雅美靓颜门店管理系统最终数据库结构
-- 只保留当前系统真实使用字段。

begin;

create table if not exists public.stores (
  id bigint generated always as identity primary key,
  name text,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid,
  name text,
  role text,
  store text,
  created_at timestamptz default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  store text,
  owner text,
  level text,
  last_visit date,
  follow_status text,
  last_follow_result text,
  last_follow_time date,
  next_follow_time date,
  created_at timestamptz default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  store text,
  role text,
  note text,
  today_followups numeric default 0,
  today_appointments numeric default 0,
  today_arrivals numeric default 0,
  today_deals numeric default 0,
  today_sales numeric default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.employee_daily_stats (
  id bigint generated by default as identity primary key,
  date date,
  employee_id bigint,
  employee_name text,
  phone text,
  store text,
  role text,
  followups numeric default 0,
  appointments numeric default 0,
  arrivals numeric default 0,
  deals numeric default 0,
  sales numeric default 0,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.followups (
  id bigint generated by default as identity primary key,
  customer_id bigint,
  customer_name text,
  customer_phone text,
  store text,
  owner text,
  method text,
  content text,
  feedback text,
  issue_type text,
  has_appointment boolean default false,
  appointment_time date,
  has_deal boolean default false,
  deal_amount numeric default 0,
  next_follow_time date,
  created_at timestamptz default now()
);

create table if not exists public.daily_reviews (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  invite_rate numeric default 0,
  appointment_rate numeric default 0,
  arrival_rate numeric default 0,
  deal_rate numeric default 0,
  deal_amount numeric default 0,
  unfinished_reason text,
  tomorrow_action text,
  created_at timestamptz default now()
);

alter table public.stores
  add column if not exists name text,
  add column if not exists created_at timestamptz default now();

alter table public.profiles
  add column if not exists user_id uuid,
  add column if not exists name text,
  add column if not exists role text,
  add column if not exists store text,
  add column if not exists created_at timestamptz default now();

alter table public.customers
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists owner text,
  add column if not exists level text,
  add column if not exists last_visit date,
  add column if not exists follow_status text,
  add column if not exists last_follow_result text,
  add column if not exists last_follow_time date,
  add column if not exists next_follow_time date,
  add column if not exists created_at timestamptz default now();

alter table public.employees
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists note text,
  add column if not exists today_followups numeric default 0,
  add column if not exists today_appointments numeric default 0,
  add column if not exists today_arrivals numeric default 0,
  add column if not exists today_deals numeric default 0,
  add column if not exists today_sales numeric default 0,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.employee_daily_stats
  add column if not exists date date,
  add column if not exists employee_id bigint,
  add column if not exists employee_name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists followups numeric default 0,
  add column if not exists appointments numeric default 0,
  add column if not exists arrivals numeric default 0,
  add column if not exists deals numeric default 0,
  add column if not exists sales numeric default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz default now(),
  add column if not exists updated_at timestamptz default now();

alter table public.followups
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists store text,
  add column if not exists owner text,
  add column if not exists method text,
  add column if not exists content text,
  add column if not exists feedback text,
  add column if not exists issue_type text,
  add column if not exists has_appointment boolean default false,
  add column if not exists appointment_time date,
  add column if not exists has_deal boolean default false,
  add column if not exists deal_amount numeric default 0,
  add column if not exists next_follow_time date,
  add column if not exists created_at timestamptz default now();

alter table public.daily_reviews
  add column if not exists date date,
  add column if not exists store text,
  add column if not exists invite_rate numeric default 0,
  add column if not exists appointment_rate numeric default 0,
  add column if not exists arrival_rate numeric default 0,
  add column if not exists deal_rate numeric default 0,
  add column if not exists deal_amount numeric default 0,
  add column if not exists unfinished_reason text,
  add column if not exists tomorrow_action text,
  add column if not exists created_at timestamptz default now();

alter table public.customers
  drop column if exists store_id,
  drop column if exists age,
  drop column if exists project,
  drop column if exists spend,
  drop column if exists remaining,
  drop column if exists status,
  drop column if exists note,
  drop column if exists beautician,
  drop column if exists staff_name,
  drop column if exists employee_name,
  drop column if exists owner_name,
  drop column if exists responsible_staff,
  drop column if exists recent_visit;

alter table public.employees
  drop column if exists today_visits,
  drop column if exists today_revenue,
  drop column if exists "todaySales",
  drop column if exists sales,
  drop column if exists today_amount,
  drop column if exists position;

alter table public.followups
  drop column if exists date;

update public.profiles
set role = case role
  when '老板' then 'boss'
  when '店长' then 'manager'
  when '美容师' then 'beautician'
  else role
end
where role in ('老板', '店长', '美容师');

update public.employees
set role = case role
  when '老板' then 'boss'
  when '店长' then 'manager'
  when '美容师' then 'beautician'
  else role
end
where role in ('老板', '店长', '美容师');

create index if not exists idx_stores_name on public.stores (name);
create index if not exists idx_profiles_user_id on public.profiles (user_id);
create index if not exists idx_profiles_role on public.profiles (role);
create index if not exists idx_profiles_store on public.profiles (store);
create index if not exists idx_customers_store on public.customers (store);
create index if not exists idx_customers_owner on public.customers (owner);
create index if not exists idx_customers_last_visit on public.customers (last_visit);
create index if not exists idx_customers_phone on public.customers (phone);
create index if not exists idx_employees_store on public.employees (store);
create index if not exists idx_employees_role on public.employees (role);
create index if not exists idx_employees_name on public.employees (name);
create unique index if not exists idx_employee_daily_stats_date_employee_id on public.employee_daily_stats (date, employee_id);
create index if not exists idx_employee_daily_stats_date on public.employee_daily_stats (date);
create index if not exists idx_employee_daily_stats_store on public.employee_daily_stats (store);
create index if not exists idx_employee_daily_stats_employee_id on public.employee_daily_stats (employee_id);
create index if not exists idx_followups_store on public.followups (store);
create index if not exists idx_followups_owner on public.followups (owner);
create index if not exists idx_followups_customer_id on public.followups (customer_id);
create index if not exists idx_followups_created_at on public.followups (created_at);
create index if not exists idx_daily_reviews_store on public.daily_reviews (store);
create index if not exists idx_daily_reviews_date on public.daily_reviews (date);
create index if not exists idx_daily_reviews_created_at on public.daily_reviews (created_at);

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where user_id = auth.uid() limit 1
$$;

create or replace function public.current_profile_store()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select store from public.profiles where user_id = auth.uid() limit 1
$$;

create or replace function public.current_profile_name()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select name from public.profiles where user_id = auth.uid() limit 1
$$;

alter table public.stores enable row level security;
alter table public.profiles enable row level security;
alter table public.customers enable row level security;
alter table public.employees enable row level security;
alter table public.employee_daily_stats enable row level security;
alter table public.followups enable row level security;
alter table public.daily_reviews enable row level security;

drop policy if exists stores_authenticated_select on public.stores;
create policy stores_authenticated_select
on public.stores for select
to authenticated
using (true);

drop policy if exists profiles_select_scope on public.profiles;
create policy profiles_select_scope
on public.profiles for select
to authenticated
using (
  user_id = auth.uid()
  or public.current_profile_role() = 'boss'
);

drop policy if exists profiles_update_self_or_boss on public.profiles;
create policy profiles_update_self_or_boss
on public.profiles for update
to authenticated
using (
  user_id = auth.uid()
  or public.current_profile_role() = 'boss'
)
with check (
  user_id = auth.uid()
  or public.current_profile_role() = 'boss'
);

drop policy if exists customers_select_scope on public.customers;
create policy customers_select_scope
on public.customers for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
);

drop policy if exists customers_insert_scope on public.customers;
create policy customers_insert_scope
on public.customers for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists customers_update_scope on public.customers;
create policy customers_update_scope
on public.customers for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and owner = public.current_profile_name())
);

drop policy if exists customers_delete_scope on public.customers;
create policy customers_delete_scope
on public.customers for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employees_select_scope on public.employees;
create policy employees_select_scope
on public.employees for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and name = public.current_profile_name())
);

drop policy if exists employees_insert_scope on public.employees;
create policy employees_insert_scope
on public.employees for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employees_update_scope on public.employees;
create policy employees_update_scope
on public.employees for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employees_delete_scope on public.employees;
create policy employees_delete_scope
on public.employees for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employee_daily_stats_select_scope on public.employee_daily_stats;
create policy employee_daily_stats_select_scope
on public.employee_daily_stats for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and employee_name = public.current_profile_name())
);

drop policy if exists employee_daily_stats_insert_scope on public.employee_daily_stats;
create policy employee_daily_stats_insert_scope
on public.employee_daily_stats for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists employee_daily_stats_update_scope on public.employee_daily_stats;
create policy employee_daily_stats_update_scope
on public.employee_daily_stats for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists followups_select_scope on public.followups;
create policy followups_select_scope
on public.followups for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
);

drop policy if exists followups_insert_scope on public.followups;
create policy followups_insert_scope
on public.followups for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and owner = public.current_profile_name())
);

drop policy if exists followups_update_scope on public.followups;
create policy followups_update_scope
on public.followups for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and store = public.current_profile_store() and owner = public.current_profile_name())
);

drop policy if exists followups_delete_scope on public.followups;
create policy followups_delete_scope
on public.followups for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
  or (public.current_profile_role() = 'beautician' and owner = public.current_profile_name())
);

drop policy if exists daily_reviews_select_scope on public.daily_reviews;
create policy daily_reviews_select_scope
on public.daily_reviews for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists daily_reviews_insert_scope on public.daily_reviews;
create policy daily_reviews_insert_scope
on public.daily_reviews for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists daily_reviews_update_scope on public.daily_reviews;
create policy daily_reviews_update_scope
on public.daily_reviews for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
)
with check (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

drop policy if exists daily_reviews_delete_scope on public.daily_reviews;
create policy daily_reviews_delete_scope
on public.daily_reviews for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (public.current_profile_role() = 'manager' and store = public.current_profile_store())
);

commit;
