-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase schema part2c
-- 执行顺序：part2a -> part2b -> part2c
-- 本段：跟进记录表 followups

create table if not exists public.followups (
  id bigint generated by default as identity primary key,
  customer_id bigint,
  customer_name text,
  customer_phone text,
  store text,
  date date,
  method text,
  owner text,
  content text,
  feedback text,
  has_appointment boolean not null default false,
  appointment_time date,
  has_deal boolean not null default false,
  deal_amount numeric not null default 0,
  next_follow_time date,
  issue_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.followups
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists store text,
  add column if not exists date date,
  add column if not exists method text,
  add column if not exists owner text,
  add column if not exists content text,
  add column if not exists feedback text,
  add column if not exists has_appointment boolean not null default false,
  add column if not exists appointment_time date,
  add column if not exists has_deal boolean not null default false,
  add column if not exists deal_amount numeric not null default 0,
  add column if not exists next_follow_time date,
  add column if not exists issue_type text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
