-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase schema part1b
-- 执行顺序：part1a -> part1b -> part1c -> part2 -> part3
-- 本段：用户资料表 profiles

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  name text,
  role text,
  store text,
  created_at timestamptz not null default now()
);

alter table public.profiles
  add column if not exists user_id uuid unique references auth.users(id) on delete cascade,
  add column if not exists name text,
  add column if not exists role text,
  add column if not exists store text,
  add column if not exists created_at timestamptz not null default now();
