-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

-- 雅美靓颜 Supabase schema part2
-- 执行顺序：part1 -> part2 -> part3
-- 本段：员工、跟进记录、每日复盘表

-- 员工表：当前前端实际使用 supabase.from('staff')
create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  phone text,
  store text,
  role text,
  today_followups integer not null default 0,
  today_appointments integer not null default 0,
  today_visits integer not null default 0,
  today_deals integer not null default 0,
  today_revenue numeric not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.staff
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists today_followups integer not null default 0,
  add column if not exists today_appointments integer not null default 0,
  add column if not exists today_visits integer not null default 0,
  add column if not exists today_deals integer not null default 0,
  add column if not exists today_revenue numeric not null default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 兼容 employees 表：前端已经统一到 staff，这里补齐给旧数据或外部报表使用。
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text,
  phone text,
  store text,
  role text,
  today_followups integer not null default 0,
  today_appointments integer not null default 0,
  today_visits integer not null default 0,
  today_deals integer not null default 0,
  today_revenue numeric not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.employees
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists store text,
  add column if not exists role text,
  add column if not exists today_followups integer not null default 0,
  add column if not exists today_appointments integer not null default 0,
  add column if not exists today_visits integer not null default 0,
  add column if not exists today_deals integer not null default 0,
  add column if not exists today_revenue numeric not null default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 跟进记录表：对应跟进记录页面
create table if not exists public.followups (
  id bigint generated by default as identity primary key,
  customer_id bigint,
  customer_name text,
  customer_phone text,
  store text,
  date date,
  method text,
  owner text,
  content text,
  feedback text,
  has_appointment boolean not null default false,
  appointment_time date,
  has_deal boolean not null default false,
  deal_amount numeric not null default 0,
  next_follow_time date,
  issue_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.followups
  add column if not exists customer_id bigint,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists store text,
  add column if not exists date date,
  add column if not exists method text,
  add column if not exists owner text,
  add column if not exists content text,
  add column if not exists feedback text,
  add column if not exists has_appointment boolean not null default false,
  add column if not exists appointment_time date,
  add column if not exists has_deal boolean not null default false,
  add column if not exists deal_amount numeric not null default 0,
  add column if not exists next_follow_time date,
  add column if not exists issue_type text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

-- 每日复盘表：对应每日复盘页面，不再使用 appointments 等旧字段。
create table if not exists public.daily_reviews (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  invite_rate numeric not null default 0,
  appointment_rate numeric not null default 0,
  arrival_rate numeric not null default 0,
  deal_rate numeric not null default 0,
  deal_amount numeric not null default 0,
  unfinished_reason text,
  tomorrow_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.daily_reviews
  add column if not exists date date,
  add column if not exists store text,
  add column if not exists invite_rate numeric not null default 0,
  add column if not exists appointment_rate numeric not null default 0,
  add column if not exists arrival_rate numeric not null default 0,
  add column if not exists deal_rate numeric not null default 0,
  add column if not exists deal_amount numeric not null default 0,
  add column if not exists unfinished_reason text,
  add column if not exists tomorrow_action text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();
