begin;

create table if not exists public.store_targets (
  id bigint generated by default as identity primary key,
  month text,
  store text,
  monthly_target numeric default 0,
  daily_target numeric default 0,
  current_sales numeric default 0,
  completion_rate numeric default 0,
  remaining_amount numeric default 0,
  created_at timestamptz default now()
);

alter table public.store_targets
  add column if not exists month text,
  add column if not exists store text,
  add column if not exists monthly_target numeric default 0,
  add column if not exists daily_target numeric default 0,
  add column if not exists current_sales numeric default 0,
  add column if not exists completion_rate numeric default 0,
  add column if not exists remaining_amount numeric default 0,
  add column if not exists created_at timestamptz default now();

create unique index if not exists idx_store_targets_month_store
on public.store_targets (month, store);

create index if not exists idx_store_targets_store
on public.store_targets (store);

create index if not exists idx_store_targets_month
on public.store_targets (month);

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where user_id = auth.uid()::text
  limit 1
$$;

create or replace function public.current_profile_store()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select store
  from public.profiles
  where user_id = auth.uid()::text
  limit 1
$$;

alter table public.store_targets enable row level security;

drop policy if exists store_targets_select_scope
on public.store_targets;

create policy store_targets_select_scope
on public.store_targets
for select
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
);

drop policy if exists store_targets_insert_scope
on public.store_targets;

create policy store_targets_insert_scope
on public.store_targets
for insert
to authenticated
with check (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
);

drop policy if exists store_targets_update_scope
on public.store_targets;

create policy store_targets_update_scope
on public.store_targets
for update
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
)
with check (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
);

drop policy if exists store_targets_delete_scope
on public.store_targets;

create policy store_targets_delete_scope
on public.store_targets
for delete
to authenticated
using (
  public.current_profile_role() = 'boss'
  or (
    public.current_profile_role() = 'manager'
    and store = public.current_profile_store()
  )
);

commit;
