-- 雅美靓颜 store_id bigint 兼容迁移
-- 适用场景：public.stores.id 是 bigint，customers/employees/cashier_orders.store_id 需要统一为 bigint。
-- 原则：不删除业务数据；如果旧 store_id 是 uuid/text，会先改名备份，再新增 bigint store_id。

begin;

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text,
  created_at timestamptz default now()
);

alter table public.stores
  add column if not exists name text,
  add column if not exists created_at timestamptz default now();

create unique index if not exists idx_stores_name_unique on public.stores (name);

insert into public.stores (name)
values
  ('龙泉1店'),
  ('龙泉2店'),
  ('龙泉金龙店'),
  ('郫县1店')
on conflict (name) do nothing;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  store text,
  created_at timestamptz default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  store text,
  role text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.cashier_orders (
  id bigint generated by default as identity primary key,
  order_no text,
  date date,
  month text,
  store_name text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.customers add column if not exists store text;
alter table public.employees add column if not exists store text;
alter table public.cashier_orders add column if not exists store_name text;

do $$
declare
  table_name text;
  current_type text;
  backup_col text;
begin
  foreach table_name in array array['customers', 'employees', 'cashier_orders'] loop
    select c.data_type
      into current_type
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.table_name = table_name
      and c.column_name = 'store_id';

    if current_type is null then
      execute format('alter table public.%I add column store_id bigint', table_name);
    elsif current_type <> 'bigint' then
      backup_col := 'store_id_' || replace(current_type, ' ', '_') || '_backup';
      if exists (
        select 1
        from information_schema.columns c
        where c.table_schema = 'public'
          and c.table_name = table_name
          and c.column_name = backup_col
      ) then
        backup_col := backup_col || '_' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISS');
      end if;

      execute format('alter table public.%I rename column store_id to %I', table_name, backup_col);
      execute format('alter table public.%I add column store_id bigint', table_name);
    end if;
  end loop;
end $$;

update public.customers c
set store_id = s.id,
    store = s.name
from public.stores s
where trim(c.store) = trim(s.name)
  and (c.store_id is null or c.store_id is distinct from s.id);

update public.employees e
set store_id = s.id,
    store = s.name
from public.stores s
where trim(e.store) = trim(s.name)
  and (e.store_id is null or e.store_id is distinct from s.id);

update public.cashier_orders o
set store_id = s.id,
    store_name = s.name
from public.stores s
where trim(o.store_name) = trim(s.name)
  and (o.store_id is null or o.store_id is distinct from s.id);

update public.customers c
set store_id = s.id,
    store = s.name
from public.stores s
where c.store_id is null
  and s.name = '龙泉1店';

update public.employees e
set store_id = s.id,
    store = s.name
from public.stores s
where e.store_id is null
  and s.name = '龙泉1店';

update public.cashier_orders o
set store_id = s.id,
    store_name = s.name
from public.stores s
where o.store_id is null
  and s.name = '龙泉1店';

create index if not exists idx_customers_store_id on public.customers (store_id);
create index if not exists idx_employees_store_id on public.employees (store_id);
create index if not exists idx_cashier_orders_store_id on public.cashier_orders (store_id);
create index if not exists idx_customers_store on public.customers (store);
create index if not exists idx_employees_store on public.employees (store);
create index if not exists idx_cashier_orders_store_name on public.cashier_orders (store_name);

commit;
