-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.stores
  add column if not exists name text,
  add column if not exists created_at timestamptz not null default now();

delete from public.stores a
using public.stores b
where a.name = b.name
  and a.id > b.id;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stores_name_unique'
      and conrelid = 'public.stores'::regclass
  ) then
    alter table public.stores
      add constraint stores_name_unique unique (name);
  end if;
end;
$$;

insert into public.stores (name)
values
  ('龙泉1店'),
  ('龙泉2店'),
  ('龙泉金龙店'),
  ('郫县1店')
on conflict (name) do nothing;

alter table public.stores enable row level security;

drop policy if exists "stores_select_authenticated" on public.stores;
create policy "stores_select_authenticated"
on public.stores
for select
to authenticated
using (auth.uid() is not null);
