-- DEPRECATED
-- DO NOT USE
-- replaced by schema_final.sql

begin;

create table if not exists public.stores (
  id bigint generated always as identity primary key,
  name text,
  created_at timestamptz default now()
);

delete from public.stores a
using public.stores b
where a.ctid < b.ctid
  and a.name = b.name;

update public.stores
set name = '郫县1店'
where btrim(name) = '郫县店';

delete from public.stores a
using public.stores b
where a.ctid < b.ctid
  and a.name = b.name;

delete from public.stores
where name is null
   or btrim(name) = ''
   or lower(btrim(name)) in ('all', 'null', 'undefined')
   or btrim(name) in ('全部', '全部门店')
   or btrim(name) not in ('龙泉1店', '龙泉2店', '龙泉金龙店', '郫县1店');

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'stores_name_unique'
      and conrelid = 'public.stores'::regclass
  ) then
    alter table public.stores
      add constraint stores_name_unique unique (name);
  end if;
end $$;

insert into public.stores (name)
values
  ('龙泉1店'),
  ('龙泉2店'),
  ('龙泉金龙店'),
  ('郫县1店')
on conflict (name) do nothing;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  store text,
  store_id bigint,
  created_at timestamptz default now()
);

alter table public.customers
  add column if not exists store text,
  add column if not exists store_id bigint;

update public.customers
set store = '郫县1店'
where btrim(store) = '郫县店';

update public.customers
set store = '龙泉1店'
where store is null
   or btrim(store) = ''
   or lower(btrim(store)) in ('all', 'null', 'undefined')
   or btrim(store) in ('全部', '全部门店')
   or btrim(store) not in ('龙泉1店', '龙泉2店', '龙泉金龙店', '郫县1店');

update public.customers c
set store_id = s.id
from public.stores s
where c.store = s.name
  and (c.store_id is null or c.store_id is distinct from s.id);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  store text,
  role text,
  created_at timestamptz default now()
);

alter table public.employees
  add column if not exists store text;

update public.employees
set store = '郫县1店'
where btrim(store) = '郫县店';

update public.employees
set store = '龙泉1店'
where store is null
   or btrim(store) = ''
   or lower(btrim(store)) in ('all', 'null', 'undefined')
   or btrim(store) in ('全部', '全部门店')
   or btrim(store) not in ('龙泉1店', '龙泉2店', '龙泉金龙店', '郫县1店');

create table if not exists public.followups (
  id bigint generated by default as identity primary key,
  customer_id bigint,
  customer_name text,
  customer_phone text,
  store text,
  owner text,
  created_at timestamptz default now()
);

alter table public.followups
  add column if not exists store text;

update public.followups
set store = '郫县1店'
where btrim(store) = '郫县店';

update public.followups
set store = '龙泉1店'
where store is null
   or btrim(store) = ''
   or lower(btrim(store)) in ('all', 'null', 'undefined')
   or btrim(store) in ('全部', '全部门店')
   or btrim(store) not in ('龙泉1店', '龙泉2店', '龙泉金龙店', '郫县1店');

create table if not exists public.daily_reviews (
  id bigint generated by default as identity primary key,
  date date,
  store text,
  created_at timestamptz default now()
);

alter table public.daily_reviews
  add column if not exists store text;

update public.daily_reviews
set store = '郫县1店'
where btrim(store) = '郫县店';

update public.daily_reviews
set store = '龙泉1店'
where store is null
   or btrim(store) = ''
   or lower(btrim(store)) in ('all', 'null', 'undefined')
   or btrim(store) in ('全部', '全部门店')
   or btrim(store) not in ('龙泉1店', '龙泉2店', '龙泉金龙店', '郫县1店');

commit;
